// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2014.4
// Copyright (C) 2014 Xilinx Inc. All rights reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module toThreshold_Dilate_0_0_1080_1920_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        p_src_rows_V_read,
        p_src_cols_V_read,
        p_src_data_stream_V_dout,
        p_src_data_stream_V_empty_n,
        p_src_data_stream_V_read,
        p_dst_data_stream_V_din,
        p_dst_data_stream_V_full_n,
        p_dst_data_stream_V_write
);

parameter    ap_const_logic_1 = 1'b1;
parameter    ap_const_logic_0 = 1'b0;
parameter    ap_ST_st1_fsm_0 = 4'b1;
parameter    ap_ST_st2_fsm_1 = 4'b10;
parameter    ap_ST_pp0_stg0_fsm_2 = 4'b100;
parameter    ap_ST_st12_fsm_3 = 4'b1000;
parameter    ap_const_lv32_0 = 32'b00000000000000000000000000000000;
parameter    ap_const_lv1_1 = 1'b1;
parameter    ap_const_lv32_1 = 32'b1;
parameter    ap_const_lv1_0 = 1'b0;
parameter    ap_const_lv32_2 = 32'b10;
parameter    ap_const_lv11_0 = 11'b00000000000;
parameter    ap_const_lv32_3 = 32'b11;
parameter    ap_const_lv4_1 = 4'b1;
parameter    ap_const_lv2_1 = 2'b1;
parameter    ap_const_lv2_0 = 2'b00;
parameter    ap_const_lv11_5 = 11'b101;
parameter    ap_const_lv11_2 = 11'b10;
parameter    ap_const_lv11_7FD = 11'b11111111101;
parameter    ap_const_lv2_3 = 2'b11;
parameter    ap_const_lv11_7FF = 11'b11111111111;
parameter    ap_const_lv11_1 = 11'b1;
parameter    ap_const_lv11_4 = 11'b100;
parameter    ap_const_lv12_FFC = 12'b111111111100;
parameter    ap_const_lv12_FFF = 12'b111111111111;
parameter    ap_const_lv32_B = 32'b1011;
parameter    ap_const_lv12_FFB = 12'b111111111011;
parameter    ap_const_lv12_FFA = 12'b111111111010;
parameter    ap_const_lv32_A = 32'b1010;
parameter    ap_const_lv10_0 = 10'b0000000000;
parameter    ap_true = 1'b1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [11:0] p_src_rows_V_read;
input  [11:0] p_src_cols_V_read;
input  [7:0] p_src_data_stream_V_dout;
input   p_src_data_stream_V_empty_n;
output   p_src_data_stream_V_read;
output  [7:0] p_dst_data_stream_V_din;
input   p_dst_data_stream_V_full_n;
output   p_dst_data_stream_V_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg p_src_data_stream_V_read;
reg p_dst_data_stream_V_write;
reg    ap_done_reg = 1'b0;
(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm = 4'b1;
reg    ap_sig_cseq_ST_st1_fsm_0;
reg    ap_sig_bdd_23;
reg   [10:0] p_025_0_i_i_reg_265;
reg    ap_sig_bdd_47;
wire   [10:0] heightloop_fu_357_p2;
reg   [10:0] heightloop_reg_1156;
wire   [10:0] widthloop_fu_363_p2;
reg   [10:0] widthloop_reg_1161;
wire   [11:0] tmp_93_cast_fu_375_p1;
reg   [11:0] tmp_93_cast_reg_1166;
wire   [1:0] p_neg228_i_i_cast_fu_383_p2;
reg   [1:0] p_neg228_i_i_cast_reg_1171;
wire   [10:0] ref_fu_389_p2;
reg   [10:0] ref_reg_1177;
wire   [11:0] ref_cast_fu_395_p1;
reg   [11:0] ref_cast_reg_1182;
wire   [0:0] tmp_95_fu_403_p2;
reg    ap_sig_cseq_ST_st2_fsm_1;
reg    ap_sig_bdd_71;
wire   [10:0] i_V_fu_408_p2;
reg   [10:0] i_V_reg_1191;
wire   [0:0] tmp_96_fu_414_p2;
reg   [0:0] tmp_96_reg_1196;
wire  signed [12:0] ImagLoc_y_cast_fu_426_p1;
reg  signed [12:0] ImagLoc_y_cast_reg_1201;
reg   [0:0] tmp_139_reg_1206;
wire   [1:0] tmp_140_fu_478_p1;
reg   [1:0] tmp_140_reg_1210;
wire  signed [12:0] y_1_cast_fu_488_p1;
reg  signed [12:0] y_1_cast_reg_1216;
wire   [1:0] tmp_141_fu_492_p1;
reg   [1:0] tmp_141_reg_1221;
wire  signed [12:0] y_1_1_cast_fu_502_p1;
reg  signed [12:0] y_1_1_cast_reg_1228;
wire   [0:0] brmerge_fu_506_p2;
reg   [0:0] brmerge_reg_1233;
wire   [0:0] tmp_98_fu_516_p2;
reg   [0:0] tmp_98_reg_1237;
reg    ap_sig_cseq_ST_pp0_stg0_fsm_2;
reg    ap_sig_bdd_102;
reg    ap_reg_ppiten_pp0_it0 = 1'b0;
reg    ap_reg_ppiten_pp0_it1 = 1'b0;
reg    ap_reg_ppiten_pp0_it2 = 1'b0;
reg    ap_reg_ppiten_pp0_it3 = 1'b0;
reg   [0:0] ap_reg_ppstg_tmp_98_reg_1237_pp0_it3;
reg   [0:0] or_cond2_reg_1254;
reg   [0:0] ap_reg_ppstg_or_cond2_reg_1254_pp0_it3;
reg    ap_sig_bdd_125;
reg    ap_reg_ppiten_pp0_it4 = 1'b0;
reg    ap_reg_ppiten_pp0_it5 = 1'b0;
reg    ap_reg_ppiten_pp0_it6 = 1'b0;
reg    ap_reg_ppiten_pp0_it7 = 1'b0;
reg   [0:0] or_cond221_i_i_reg_1246;
reg   [0:0] ap_reg_ppstg_or_cond221_i_i_reg_1246_pp0_it7;
reg    ap_sig_bdd_141;
reg    ap_reg_ppiten_pp0_it8 = 1'b0;
reg   [0:0] ap_reg_ppstg_tmp_98_reg_1237_pp0_it1;
reg   [0:0] ap_reg_ppstg_tmp_98_reg_1237_pp0_it2;
reg   [0:0] ap_reg_ppstg_tmp_98_reg_1237_pp0_it4;
reg   [0:0] ap_reg_ppstg_tmp_98_reg_1237_pp0_it5;
reg   [0:0] ap_reg_ppstg_tmp_98_reg_1237_pp0_it6;
wire   [10:0] j_V_fu_521_p2;
wire   [0:0] or_cond221_i_i_fu_543_p2;
reg   [0:0] ap_reg_ppstg_or_cond221_i_i_reg_1246_pp0_it1;
reg   [0:0] ap_reg_ppstg_or_cond221_i_i_reg_1246_pp0_it2;
reg   [0:0] ap_reg_ppstg_or_cond221_i_i_reg_1246_pp0_it3;
reg   [0:0] ap_reg_ppstg_or_cond221_i_i_reg_1246_pp0_it4;
reg   [0:0] ap_reg_ppstg_or_cond221_i_i_reg_1246_pp0_it5;
reg   [0:0] ap_reg_ppstg_or_cond221_i_i_reg_1246_pp0_it6;
wire   [0:0] tmp_106_fu_569_p2;
reg   [0:0] tmp_106_reg_1250;
reg   [0:0] ap_reg_ppstg_tmp_106_reg_1250_pp0_it1;
reg   [0:0] ap_reg_ppstg_tmp_106_reg_1250_pp0_it2;
reg   [0:0] ap_reg_ppstg_tmp_106_reg_1250_pp0_it3;
reg   [0:0] ap_reg_ppstg_tmp_106_reg_1250_pp0_it4;
wire   [0:0] or_cond2_fu_574_p2;
reg   [0:0] ap_reg_ppstg_or_cond2_reg_1254_pp0_it1;
reg   [0:0] ap_reg_ppstg_or_cond2_reg_1254_pp0_it2;
reg   [0:0] ap_reg_ppstg_or_cond2_reg_1254_pp0_it4;
reg   [0:0] tmp_145_reg_1258;
reg   [0:0] ap_reg_ppstg_tmp_145_reg_1258_pp0_it1;
reg   [0:0] ap_reg_ppstg_tmp_145_reg_1258_pp0_it2;
reg   [0:0] ap_reg_ppstg_tmp_145_reg_1258_pp0_it3;
reg   [0:0] ap_reg_ppstg_tmp_145_reg_1258_pp0_it4;
wire   [0:0] tmp_107_fu_588_p2;
reg   [0:0] tmp_107_reg_1262;
reg   [0:0] ap_reg_ppstg_tmp_107_reg_1262_pp0_it1;
reg   [0:0] ap_reg_ppstg_tmp_107_reg_1262_pp0_it2;
reg   [0:0] ap_reg_ppstg_tmp_107_reg_1262_pp0_it3;
wire   [1:0] col_assign_fu_593_p2;
reg   [1:0] col_assign_reg_1266;
reg   [1:0] ap_reg_ppstg_col_assign_reg_1266_pp0_it1;
reg   [1:0] ap_reg_ppstg_col_assign_reg_1266_pp0_it2;
reg   [1:0] ap_reg_ppstg_col_assign_reg_1266_pp0_it3;
wire   [14:0] grp_toThreshold_borderInterpolate_fu_277_ap_return;
reg   [14:0] x_reg_1272;
wire   [1:0] tmp_144_fu_598_p1;
reg   [1:0] tmp_144_reg_1277;
wire   [1:0] tmp_148_fu_602_p1;
reg   [1:0] tmp_148_reg_1282;
reg   [10:0] k_buf_0_val_0_addr_reg_1287;
reg   [10:0] k_buf_0_val_1_addr_reg_1293;
reg   [10:0] k_buf_0_val_2_addr_reg_1299;
wire   [1:0] locy_2_t_fu_616_p2;
reg   [1:0] locy_2_t_reg_1305;
reg   [1:0] ap_reg_ppstg_locy_2_t_reg_1305_pp0_it4;
wire   [1:0] col_assign_2_fu_620_p2;
reg   [1:0] col_assign_2_reg_1309;
reg   [1:0] ap_reg_ppstg_col_assign_2_reg_1309_pp0_it4;
wire   [7:0] k_buf_0_val_0_q0;
reg   [7:0] right_border_buf_0_val_2_0_reg_1315;
wire   [7:0] k_buf_0_val_1_q0;
reg   [7:0] right_border_buf_0_val_1_0_reg_1320;
wire   [7:0] k_buf_0_val_2_q0;
reg   [7:0] src_kernel_win_0_val_2_0_reg_1328;
wire   [1:0] tmp_146_fu_629_p1;
reg   [1:0] tmp_146_reg_1335;
wire   [1:0] tmp_147_fu_633_p1;
reg   [1:0] tmp_147_reg_1341;
reg   [7:0] src_kernel_win_0_val_0_1_24_reg_1347;
reg   [7:0] ap_reg_ppstg_src_kernel_win_0_val_0_1_24_reg_1347_pp0_it6;
reg   [7:0] ap_reg_ppstg_src_kernel_win_0_val_0_1_24_reg_1347_pp0_it7;
reg   [7:0] src_kernel_win_0_val_1_1_24_reg_1354;
reg   [7:0] ap_reg_ppstg_src_kernel_win_0_val_1_1_24_reg_1354_pp0_it6;
wire   [7:0] temp_0_i_i_i_057_i_i_1_0_1_fu_909_p3;
reg   [7:0] temp_0_i_i_i_057_i_i_1_0_1_reg_1361;
reg   [7:0] src_kernel_win_0_val_0_1_lo_reg_1367;
reg   [7:0] ap_reg_ppstg_src_kernel_win_0_val_0_1_lo_reg_1367_pp0_it7;
reg   [7:0] src_kernel_win_0_val_1_1_lo_reg_1373;
wire   [7:0] temp_0_i_i_i_057_i_i_1_1_fu_952_p3;
reg   [7:0] temp_0_i_i_i_057_i_i_1_1_reg_1379;
wire   [0:0] tmp_192_1_1_fu_960_p2;
reg   [0:0] tmp_192_1_1_reg_1384;
wire   [7:0] temp_0_i_i_i_057_i_i_1_2_fu_995_p3;
reg   [7:0] temp_0_i_i_i_057_i_i_1_2_reg_1389;
wire   [10:0] k_buf_0_val_0_address0;
reg    k_buf_0_val_0_ce0;
wire   [10:0] k_buf_0_val_0_address1;
reg    k_buf_0_val_0_ce1;
reg    k_buf_0_val_0_we1;
wire   [7:0] k_buf_0_val_0_d1;
wire   [10:0] k_buf_0_val_1_address0;
reg    k_buf_0_val_1_ce0;
wire   [10:0] k_buf_0_val_1_address1;
reg    k_buf_0_val_1_ce1;
reg    k_buf_0_val_1_we1;
wire   [7:0] k_buf_0_val_1_d1;
wire   [10:0] k_buf_0_val_2_address0;
reg    k_buf_0_val_2_ce0;
wire   [10:0] k_buf_0_val_2_address1;
reg    k_buf_0_val_2_ce1;
reg    k_buf_0_val_2_we1;
wire   [7:0] k_buf_0_val_2_d1;
wire   [12:0] grp_toThreshold_borderInterpolate_fu_277_p;
wire   [11:0] grp_toThreshold_borderInterpolate_fu_277_len;
wire   [3:0] grp_toThreshold_borderInterpolate_fu_277_borderType;
reg    grp_toThreshold_borderInterpolate_fu_277_ap_ce;
wire   [12:0] grp_toThreshold_borderInterpolate_fu_285_p;
wire   [11:0] grp_toThreshold_borderInterpolate_fu_285_len;
wire   [3:0] grp_toThreshold_borderInterpolate_fu_285_borderType;
wire   [14:0] grp_toThreshold_borderInterpolate_fu_285_ap_return;
reg    grp_toThreshold_borderInterpolate_fu_285_ap_ce;
wire   [12:0] grp_toThreshold_borderInterpolate_fu_293_p;
wire   [11:0] grp_toThreshold_borderInterpolate_fu_293_len;
wire   [3:0] grp_toThreshold_borderInterpolate_fu_293_borderType;
wire   [14:0] grp_toThreshold_borderInterpolate_fu_293_ap_return;
reg    grp_toThreshold_borderInterpolate_fu_293_ap_ce;
wire   [12:0] grp_toThreshold_borderInterpolate_fu_301_p;
wire   [11:0] grp_toThreshold_borderInterpolate_fu_301_len;
wire   [3:0] grp_toThreshold_borderInterpolate_fu_301_borderType;
wire   [14:0] grp_toThreshold_borderInterpolate_fu_301_ap_return;
reg    grp_toThreshold_borderInterpolate_fu_301_ap_ce;
reg   [10:0] p_012_0_i_i_reg_254;
reg    ap_sig_cseq_ST_st12_fsm_3;
reg    ap_sig_bdd_384;
wire   [63:0] tmp_s_fu_609_p1;
reg   [7:0] src_kernel_win_0_val_0_1_fu_108;
wire   [7:0] src_kernel_win_0_val_0_0_fu_762_p3;
wire   [7:0] col_buf_0_val_0_0_46_fu_850_p3;
reg   [7:0] src_kernel_win_0_val_0_2_fu_112;
reg   [7:0] col_buf_0_val_0_0_39_fu_116;
reg   [7:0] src_kernel_win_0_val_2_1_fu_120;
reg   [7:0] src_kernel_win_0_val_1_1_fu_124;
wire   [7:0] src_kernel_win_0_val_1_0_fu_794_p3;
wire   [7:0] right_border_buf_0_val_1_2_20_fu_867_p3;
reg   [7:0] src_kernel_win_0_val_1_2_fu_128;
reg   [7:0] col_buf_0_val_0_0_40_fu_132;
reg   [7:0] src_kernel_win_0_val_2_2_fu_136;
reg   [7:0] col_buf_0_val_0_0_41_fu_140;
reg   [7:0] right_border_buf_0_val_1_2_14_fu_144;
wire   [7:0] right_border_buf_0_val_1_2_19_fu_705_p3;
reg   [7:0] right_border_buf_0_val_1_2_15_fu_148;
wire   [7:0] right_border_buf_0_val_1_2_5_fu_696_p3;
reg   [7:0] right_border_buf_0_val_1_2_16_fu_152;
wire   [7:0] right_border_buf_0_val_1_2_3_fu_679_p3;
reg   [7:0] right_border_buf_0_val_0_0_fu_168;
reg   [7:0] right_border_buf_0_val_0_1_fu_172;
reg   [7:0] right_border_buf_0_val_0_2_fu_176;
reg   [7:0] col_buf_0_val_0_0_fu_180;
wire   [10:0] tmp_fu_349_p1;
wire   [10:0] tmp_136_fu_353_p1;
wire   [10:0] tmp_93_fu_369_p2;
wire   [1:0] tmp_137_fu_379_p1;
wire   [11:0] tmp_94_cast_cast3_fu_399_p1;
wire   [11:0] ImagLoc_y_fu_420_p2;
wire   [10:0] tmp_138_fu_436_p4;
wire   [0:0] icmp_fu_446_p2;
wire   [0:0] tmp_103_fu_452_p2;
wire   [10:0] p_i_i_fu_471_p3;
wire   [11:0] y_1_fu_482_p2;
wire   [11:0] y_1_1_fu_496_p2;
wire   [0:0] tmp_102_fu_430_p2;
wire   [0:0] or_cond_fu_457_p2;
wire   [9:0] tmp_142_fu_527_p4;
wire   [0:0] icmp4_fu_537_p2;
wire   [11:0] tmp_97_cast_fu_512_p1;
wire   [11:0] ImagLoc_x_fu_548_p2;
wire   [0:0] tmp_105_fu_563_p2;
wire   [1:0] tmp_143_fu_554_p1;
wire  signed [31:0] x_4_fu_606_p1;
wire   [0:0] sel_tmp16_fu_661_p2;
wire   [0:0] sel_tmp18_fu_674_p2;
wire   [7:0] right_border_buf_0_val_1_2_2_fu_666_p3;
wire   [7:0] right_border_buf_0_val_1_2_4_fu_688_p3;
wire   [0:0] sel_tmp8_fu_745_p2;
wire   [1:0] locy_fu_738_p2;
wire   [0:0] sel_tmp10_fu_756_p2;
wire   [7:0] sel_tmp9_fu_749_p3;
wire   [0:0] sel_tmp12_fu_777_p2;
wire   [1:0] locy_1_t_fu_770_p2;
wire   [0:0] sel_tmp14_fu_788_p2;
wire   [7:0] sel_tmp13_fu_781_p3;
wire   [0:0] sel_tmp_fu_832_p2;
wire   [0:0] sel_tmp2_fu_845_p2;
wire   [7:0] col_buf_0_val_0_0_42_fu_837_p3;
wire   [7:0] right_border_buf_0_val_1_2_fu_859_p3;
wire   [0:0] tmp_192_0_1_fu_903_p2;
wire   [0:0] tmp_192_0_2_fu_934_p2;
wire   [7:0] temp_0_i_i_i_057_i_i_1_0_2_fu_939_p3;
wire   [0:0] tmp_192_1_fu_946_p2;
wire   [7:0] temp_0_i_i_i_057_i_i_1_1_1_fu_972_p3;
wire   [0:0] tmp_192_1_2_fu_977_p2;
wire   [7:0] temp_0_i_i_i_057_i_i_1_1_2_fu_982_p3;
wire   [0:0] tmp_192_2_fu_989_p2;
wire   [0:0] tmp_192_2_1_fu_1007_p2;
wire   [7:0] temp_0_i_i_i_057_i_i_1_2_1_fu_1011_p3;
wire   [0:0] tmp_192_2_2_fu_1017_p2;
reg   [3:0] ap_NS_fsm;


toThreshold_Dilate_0_0_1080_1920_s_k_buf_0_val_0 #(
    .DataWidth( 8 ),
    .AddressRange( 1920 ),
    .AddressWidth( 11 ))
k_buf_0_val_0_U(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .address0( k_buf_0_val_0_address0 ),
    .ce0( k_buf_0_val_0_ce0 ),
    .q0( k_buf_0_val_0_q0 ),
    .address1( k_buf_0_val_0_address1 ),
    .ce1( k_buf_0_val_0_ce1 ),
    .we1( k_buf_0_val_0_we1 ),
    .d1( k_buf_0_val_0_d1 )
);

toThreshold_Dilate_0_0_1080_1920_s_k_buf_0_val_0 #(
    .DataWidth( 8 ),
    .AddressRange( 1920 ),
    .AddressWidth( 11 ))
k_buf_0_val_1_U(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .address0( k_buf_0_val_1_address0 ),
    .ce0( k_buf_0_val_1_ce0 ),
    .q0( k_buf_0_val_1_q0 ),
    .address1( k_buf_0_val_1_address1 ),
    .ce1( k_buf_0_val_1_ce1 ),
    .we1( k_buf_0_val_1_we1 ),
    .d1( k_buf_0_val_1_d1 )
);

toThreshold_Dilate_0_0_1080_1920_s_k_buf_0_val_0 #(
    .DataWidth( 8 ),
    .AddressRange( 1920 ),
    .AddressWidth( 11 ))
k_buf_0_val_2_U(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .address0( k_buf_0_val_2_address0 ),
    .ce0( k_buf_0_val_2_ce0 ),
    .q0( k_buf_0_val_2_q0 ),
    .address1( k_buf_0_val_2_address1 ),
    .ce1( k_buf_0_val_2_ce1 ),
    .we1( k_buf_0_val_2_we1 ),
    .d1( k_buf_0_val_2_d1 )
);

toThreshold_borderInterpolate grp_toThreshold_borderInterpolate_fu_277(
    .ap_clk( ap_clk ),
    .ap_rst( ap_rst ),
    .p( grp_toThreshold_borderInterpolate_fu_277_p ),
    .len( grp_toThreshold_borderInterpolate_fu_277_len ),
    .borderType( grp_toThreshold_borderInterpolate_fu_277_borderType ),
    .ap_return( grp_toThreshold_borderInterpolate_fu_277_ap_return ),
    .ap_ce( grp_toThreshold_borderInterpolate_fu_277_ap_ce )
);

toThreshold_borderInterpolate grp_toThreshold_borderInterpolate_fu_285(
    .ap_clk( ap_clk ),
    .ap_rst( ap_rst ),
    .p( grp_toThreshold_borderInterpolate_fu_285_p ),
    .len( grp_toThreshold_borderInterpolate_fu_285_len ),
    .borderType( grp_toThreshold_borderInterpolate_fu_285_borderType ),
    .ap_return( grp_toThreshold_borderInterpolate_fu_285_ap_return ),
    .ap_ce( grp_toThreshold_borderInterpolate_fu_285_ap_ce )
);

toThreshold_borderInterpolate grp_toThreshold_borderInterpolate_fu_293(
    .ap_clk( ap_clk ),
    .ap_rst( ap_rst ),
    .p( grp_toThreshold_borderInterpolate_fu_293_p ),
    .len( grp_toThreshold_borderInterpolate_fu_293_len ),
    .borderType( grp_toThreshold_borderInterpolate_fu_293_borderType ),
    .ap_return( grp_toThreshold_borderInterpolate_fu_293_ap_return ),
    .ap_ce( grp_toThreshold_borderInterpolate_fu_293_ap_ce )
);

toThreshold_borderInterpolate grp_toThreshold_borderInterpolate_fu_301(
    .ap_clk( ap_clk ),
    .ap_rst( ap_rst ),
    .p( grp_toThreshold_borderInterpolate_fu_301_p ),
    .len( grp_toThreshold_borderInterpolate_fu_301_len ),
    .borderType( grp_toThreshold_borderInterpolate_fu_301_borderType ),
    .ap_return( grp_toThreshold_borderInterpolate_fu_301_ap_return ),
    .ap_ce( grp_toThreshold_borderInterpolate_fu_301_ap_ce )
);



/// the current state (ap_CS_fsm) of the state machine. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_CS_fsm
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_st1_fsm_0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

/// ap_done_reg assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_done_reg
    if (ap_rst == 1'b1) begin
        ap_done_reg <= ap_const_logic_0;
    end else begin
        if ((ap_const_logic_1 == ap_continue)) begin
            ap_done_reg <= ap_const_logic_0;
        end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & (tmp_95_fu_403_p2 == ap_const_lv1_0))) begin
            ap_done_reg <= ap_const_logic_1;
        end
    end
end

/// ap_reg_ppiten_pp0_it0 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it0
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it0 <= ap_const_logic_0;
    end else begin
        if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & ~((ap_sig_bdd_125 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4)) | (ap_sig_bdd_141 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it8))) & (ap_const_lv1_0 == tmp_98_fu_516_p2))) begin
            ap_reg_ppiten_pp0_it0 <= ap_const_logic_0;
        end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & ~(tmp_95_fu_403_p2 == ap_const_lv1_0))) begin
            ap_reg_ppiten_pp0_it0 <= ap_const_logic_1;
        end
    end
end

/// ap_reg_ppiten_pp0_it1 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it1
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it1 <= ap_const_logic_0;
    end else begin
        if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & ~((ap_sig_bdd_125 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4)) | (ap_sig_bdd_141 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it8))))) begin
            ap_reg_ppiten_pp0_it1 <= ap_reg_ppiten_pp0_it0;
        end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & ~(tmp_95_fu_403_p2 == ap_const_lv1_0))) begin
            ap_reg_ppiten_pp0_it1 <= ap_const_logic_0;
        end
    end
end

/// ap_reg_ppiten_pp0_it2 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it2
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it2 <= ap_const_logic_0;
    end else begin
        if (~((ap_sig_bdd_125 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4)) | (ap_sig_bdd_141 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it8)))) begin
            ap_reg_ppiten_pp0_it2 <= ap_reg_ppiten_pp0_it1;
        end
    end
end

/// ap_reg_ppiten_pp0_it3 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it3
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it3 <= ap_const_logic_0;
    end else begin
        if (~((ap_sig_bdd_125 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4)) | (ap_sig_bdd_141 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it8)))) begin
            ap_reg_ppiten_pp0_it3 <= ap_reg_ppiten_pp0_it2;
        end
    end
end

/// ap_reg_ppiten_pp0_it4 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it4
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it4 <= ap_const_logic_0;
    end else begin
        if (~((ap_sig_bdd_125 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4)) | (ap_sig_bdd_141 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it8)))) begin
            ap_reg_ppiten_pp0_it4 <= ap_reg_ppiten_pp0_it3;
        end
    end
end

/// ap_reg_ppiten_pp0_it5 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it5
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it5 <= ap_const_logic_0;
    end else begin
        if (~((ap_sig_bdd_125 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4)) | (ap_sig_bdd_141 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it8)))) begin
            ap_reg_ppiten_pp0_it5 <= ap_reg_ppiten_pp0_it4;
        end
    end
end

/// ap_reg_ppiten_pp0_it6 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it6
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it6 <= ap_const_logic_0;
    end else begin
        if (~((ap_sig_bdd_125 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4)) | (ap_sig_bdd_141 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it8)))) begin
            if (~(ap_const_logic_1 == ap_reg_ppiten_pp0_it4)) begin
                ap_reg_ppiten_pp0_it6 <= ap_const_logic_0;
            end else if ((ap_const_logic_1 == ap_reg_ppiten_pp0_it4)) begin
                ap_reg_ppiten_pp0_it6 <= ap_reg_ppiten_pp0_it5;
            end
        end
    end
end

/// ap_reg_ppiten_pp0_it7 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it7
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it7 <= ap_const_logic_0;
    end else begin
        if (~((ap_sig_bdd_125 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4)) | (ap_sig_bdd_141 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it8)))) begin
            ap_reg_ppiten_pp0_it7 <= ap_reg_ppiten_pp0_it6;
        end
    end
end

/// ap_reg_ppiten_pp0_it8 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it8
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it8 <= ap_const_logic_0;
    end else begin
        if (~((ap_sig_bdd_125 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4)) | (ap_sig_bdd_141 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it8)))) begin
            ap_reg_ppiten_pp0_it8 <= ap_reg_ppiten_pp0_it7;
        end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & ~(tmp_95_fu_403_p2 == ap_const_lv1_0))) begin
            ap_reg_ppiten_pp0_it8 <= ap_const_logic_0;
        end
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st12_fsm_3)) begin
        p_012_0_i_i_reg_254 <= i_V_reg_1191;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & ~ap_sig_bdd_47)) begin
        p_012_0_i_i_reg_254 <= ap_const_lv11_0;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_sig_bdd_125 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4)) | (ap_sig_bdd_141 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it8))) & ~(ap_const_lv1_0 == tmp_98_fu_516_p2))) begin
        p_025_0_i_i_reg_265 <= j_V_fu_521_p2;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & ~(tmp_95_fu_403_p2 == ap_const_lv1_0))) begin
        p_025_0_i_i_reg_265 <= ap_const_lv11_0;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((~(ap_const_lv1_0 == brmerge_reg_1233) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it5) & ~((ap_sig_bdd_125 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4)) | (ap_sig_bdd_141 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it8))) & ~(ap_const_lv1_0 == ap_reg_ppstg_tmp_98_reg_1237_pp0_it4) & (ap_const_lv1_0 == ap_reg_ppstg_or_cond2_reg_1254_pp0_it4) & ~(ap_const_lv1_0 == ap_reg_ppstg_tmp_145_reg_1258_pp0_it4)) | (~(ap_const_lv1_0 == brmerge_reg_1233) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it5) & ~((ap_sig_bdd_125 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4)) | (ap_sig_bdd_141 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it8))) & ~(ap_const_lv1_0 == ap_reg_ppstg_tmp_98_reg_1237_pp0_it4) & ~(ap_const_lv1_0 == ap_reg_ppstg_or_cond2_reg_1254_pp0_it4)))) begin
        src_kernel_win_0_val_0_1_fu_108 <= right_border_buf_0_val_2_0_reg_1315;
    end else if (((~(ap_const_lv1_0 == brmerge_reg_1233) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it5) & ~((ap_sig_bdd_125 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4)) | (ap_sig_bdd_141 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it8))) & ~(ap_const_lv1_0 == ap_reg_ppstg_tmp_98_reg_1237_pp0_it4) & (ap_const_lv1_0 == ap_reg_ppstg_or_cond2_reg_1254_pp0_it4) & (ap_const_lv1_0 == ap_reg_ppstg_tmp_145_reg_1258_pp0_it4) & (ap_const_lv1_0 == ap_reg_ppstg_tmp_106_reg_1250_pp0_it4) & (ap_reg_ppstg_col_assign_2_reg_1309_pp0_it4 == ap_const_lv2_1)) | (~(ap_const_lv1_0 == brmerge_reg_1233) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it5) & ~((ap_sig_bdd_125 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4)) | (ap_sig_bdd_141 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it8))) & ~(ap_const_lv1_0 == ap_reg_ppstg_tmp_98_reg_1237_pp0_it4) & (ap_const_lv1_0 == ap_reg_ppstg_or_cond2_reg_1254_pp0_it4) & (ap_const_lv1_0 == ap_reg_ppstg_tmp_145_reg_1258_pp0_it4) & (ap_const_lv1_0 == ap_reg_ppstg_tmp_106_reg_1250_pp0_it4) & (ap_reg_ppstg_col_assign_2_reg_1309_pp0_it4 == ap_const_lv2_0)) | (~(ap_const_lv1_0 == brmerge_reg_1233) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it5) & ~((ap_sig_bdd_125 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4)) | (ap_sig_bdd_141 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it8))) & ~(ap_const_lv1_0 == ap_reg_ppstg_tmp_98_reg_1237_pp0_it4) & (ap_const_lv1_0 == ap_reg_ppstg_or_cond2_reg_1254_pp0_it4) & (ap_const_lv1_0 == ap_reg_ppstg_tmp_145_reg_1258_pp0_it4) & (ap_const_lv1_0 == ap_reg_ppstg_tmp_106_reg_1250_pp0_it4) & ~(ap_reg_ppstg_col_assign_2_reg_1309_pp0_it4 == ap_const_lv2_1) & ~(ap_reg_ppstg_col_assign_2_reg_1309_pp0_it4 == ap_const_lv2_0)))) begin
        src_kernel_win_0_val_0_1_fu_108 <= col_buf_0_val_0_0_46_fu_850_p3;
    end else if ((((ap_const_lv1_0 == brmerge_reg_1233) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it5) & ~((ap_sig_bdd_125 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4)) | (ap_sig_bdd_141 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it8))) & (ap_const_lv1_0 == tmp_139_reg_1206) & ~(ap_const_lv1_0 == ap_reg_ppstg_tmp_98_reg_1237_pp0_it4) & (ap_reg_ppstg_locy_2_t_reg_1305_pp0_it4 == ap_const_lv2_1)) | ((ap_const_lv1_0 == brmerge_reg_1233) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it5) & ~((ap_sig_bdd_125 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4)) | (ap_sig_bdd_141 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it8))) & (ap_const_lv1_0 == tmp_139_reg_1206) & ~(ap_const_lv1_0 == ap_reg_ppstg_tmp_98_reg_1237_pp0_it4) & (ap_reg_ppstg_locy_2_t_reg_1305_pp0_it4 == ap_const_lv2_0)) | ((ap_const_lv1_0 == brmerge_reg_1233) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it5) & ~((ap_sig_bdd_125 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4)) | (ap_sig_bdd_141 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it8))) & (ap_const_lv1_0 == tmp_139_reg_1206) & ~(ap_const_lv1_0 == ap_reg_ppstg_tmp_98_reg_1237_pp0_it4) & ~(ap_reg_ppstg_locy_2_t_reg_1305_pp0_it4 == ap_const_lv2_1) & ~(ap_reg_ppstg_locy_2_t_reg_1305_pp0_it4 == ap_const_lv2_0)))) begin
        src_kernel_win_0_val_0_1_fu_108 <= src_kernel_win_0_val_0_0_fu_762_p3;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((~(ap_const_lv1_0 == brmerge_reg_1233) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it5) & ~((ap_sig_bdd_125 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4)) | (ap_sig_bdd_141 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it8))) & ~(ap_const_lv1_0 == ap_reg_ppstg_tmp_98_reg_1237_pp0_it4) & (ap_const_lv1_0 == ap_reg_ppstg_or_cond2_reg_1254_pp0_it4) & ~(ap_const_lv1_0 == ap_reg_ppstg_tmp_145_reg_1258_pp0_it4)) | (~(ap_const_lv1_0 == brmerge_reg_1233) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it5) & ~((ap_sig_bdd_125 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4)) | (ap_sig_bdd_141 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it8))) & ~(ap_const_lv1_0 == ap_reg_ppstg_tmp_98_reg_1237_pp0_it4) & ~(ap_const_lv1_0 == ap_reg_ppstg_or_cond2_reg_1254_pp0_it4)))) begin
        src_kernel_win_0_val_1_1_fu_124 <= right_border_buf_0_val_1_0_reg_1320;
    end else if (((~(ap_const_lv1_0 == brmerge_reg_1233) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it5) & ~((ap_sig_bdd_125 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4)) | (ap_sig_bdd_141 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it8))) & ~(ap_const_lv1_0 == ap_reg_ppstg_tmp_98_reg_1237_pp0_it4) & (ap_const_lv1_0 == ap_reg_ppstg_or_cond2_reg_1254_pp0_it4) & (ap_const_lv1_0 == ap_reg_ppstg_tmp_145_reg_1258_pp0_it4) & (ap_const_lv1_0 == ap_reg_ppstg_tmp_106_reg_1250_pp0_it4) & (ap_reg_ppstg_col_assign_2_reg_1309_pp0_it4 == ap_const_lv2_1)) | (~(ap_const_lv1_0 == brmerge_reg_1233) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it5) & ~((ap_sig_bdd_125 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4)) | (ap_sig_bdd_141 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it8))) & ~(ap_const_lv1_0 == ap_reg_ppstg_tmp_98_reg_1237_pp0_it4) & (ap_const_lv1_0 == ap_reg_ppstg_or_cond2_reg_1254_pp0_it4) & (ap_const_lv1_0 == ap_reg_ppstg_tmp_145_reg_1258_pp0_it4) & (ap_const_lv1_0 == ap_reg_ppstg_tmp_106_reg_1250_pp0_it4) & (ap_reg_ppstg_col_assign_2_reg_1309_pp0_it4 == ap_const_lv2_0)) | (~(ap_const_lv1_0 == brmerge_reg_1233) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it5) & ~((ap_sig_bdd_125 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4)) | (ap_sig_bdd_141 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it8))) & ~(ap_const_lv1_0 == ap_reg_ppstg_tmp_98_reg_1237_pp0_it4) & (ap_const_lv1_0 == ap_reg_ppstg_or_cond2_reg_1254_pp0_it4) & (ap_const_lv1_0 == ap_reg_ppstg_tmp_145_reg_1258_pp0_it4) & (ap_const_lv1_0 == ap_reg_ppstg_tmp_106_reg_1250_pp0_it4) & ~(ap_reg_ppstg_col_assign_2_reg_1309_pp0_it4 == ap_const_lv2_1) & ~(ap_reg_ppstg_col_assign_2_reg_1309_pp0_it4 == ap_const_lv2_0)))) begin
        src_kernel_win_0_val_1_1_fu_124 <= right_border_buf_0_val_1_2_20_fu_867_p3;
    end else if ((((ap_const_lv1_0 == brmerge_reg_1233) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it5) & ~((ap_sig_bdd_125 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4)) | (ap_sig_bdd_141 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it8))) & (ap_const_lv1_0 == tmp_139_reg_1206) & ~(ap_const_lv1_0 == ap_reg_ppstg_tmp_98_reg_1237_pp0_it4) & (ap_reg_ppstg_locy_2_t_reg_1305_pp0_it4 == ap_const_lv2_1)) | ((ap_const_lv1_0 == brmerge_reg_1233) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it5) & ~((ap_sig_bdd_125 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4)) | (ap_sig_bdd_141 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it8))) & (ap_const_lv1_0 == tmp_139_reg_1206) & ~(ap_const_lv1_0 == ap_reg_ppstg_tmp_98_reg_1237_pp0_it4) & (ap_reg_ppstg_locy_2_t_reg_1305_pp0_it4 == ap_const_lv2_0)) | ((ap_const_lv1_0 == brmerge_reg_1233) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it5) & ~((ap_sig_bdd_125 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4)) | (ap_sig_bdd_141 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it8))) & (ap_const_lv1_0 == tmp_139_reg_1206) & ~(ap_const_lv1_0 == ap_reg_ppstg_tmp_98_reg_1237_pp0_it4) & ~(ap_reg_ppstg_locy_2_t_reg_1305_pp0_it4 == ap_const_lv2_1) & ~(ap_reg_ppstg_locy_2_t_reg_1305_pp0_it4 == ap_const_lv2_0)))) begin
        src_kernel_win_0_val_1_1_fu_124 <= src_kernel_win_0_val_1_0_fu_794_p3;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((~(ap_const_lv1_0 == brmerge_reg_1233) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it5) & ~((ap_sig_bdd_125 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4)) | (ap_sig_bdd_141 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it8))) & ~(ap_const_lv1_0 == ap_reg_ppstg_tmp_98_reg_1237_pp0_it4) & (ap_const_lv1_0 == ap_reg_ppstg_or_cond2_reg_1254_pp0_it4) & (ap_const_lv1_0 == ap_reg_ppstg_tmp_145_reg_1258_pp0_it4) & (ap_const_lv1_0 == ap_reg_ppstg_tmp_106_reg_1250_pp0_it4) & ~(ap_reg_ppstg_col_assign_2_reg_1309_pp0_it4 == ap_const_lv2_1) & ~(ap_reg_ppstg_col_assign_2_reg_1309_pp0_it4 == ap_const_lv2_0))) begin
        src_kernel_win_0_val_2_1_fu_120 <= right_border_buf_0_val_0_2_fu_176;
    end else if ((~(ap_const_lv1_0 == brmerge_reg_1233) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it5) & ~((ap_sig_bdd_125 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4)) | (ap_sig_bdd_141 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it8))) & ~(ap_const_lv1_0 == ap_reg_ppstg_tmp_98_reg_1237_pp0_it4) & (ap_const_lv1_0 == ap_reg_ppstg_or_cond2_reg_1254_pp0_it4) & (ap_const_lv1_0 == ap_reg_ppstg_tmp_145_reg_1258_pp0_it4) & (ap_const_lv1_0 == ap_reg_ppstg_tmp_106_reg_1250_pp0_it4) & (ap_reg_ppstg_col_assign_2_reg_1309_pp0_it4 == ap_const_lv2_0))) begin
        src_kernel_win_0_val_2_1_fu_120 <= right_border_buf_0_val_0_0_fu_168;
    end else if ((~(ap_const_lv1_0 == brmerge_reg_1233) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it5) & ~((ap_sig_bdd_125 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4)) | (ap_sig_bdd_141 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it8))) & ~(ap_const_lv1_0 == ap_reg_ppstg_tmp_98_reg_1237_pp0_it4) & (ap_const_lv1_0 == ap_reg_ppstg_or_cond2_reg_1254_pp0_it4) & (ap_const_lv1_0 == ap_reg_ppstg_tmp_145_reg_1258_pp0_it4) & (ap_const_lv1_0 == ap_reg_ppstg_tmp_106_reg_1250_pp0_it4) & (ap_reg_ppstg_col_assign_2_reg_1309_pp0_it4 == ap_const_lv2_1))) begin
        src_kernel_win_0_val_2_1_fu_120 <= right_border_buf_0_val_0_1_fu_172;
    end else if ((((ap_const_lv1_0 == brmerge_reg_1233) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it5) & ~((ap_sig_bdd_125 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4)) | (ap_sig_bdd_141 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it8))) & (ap_const_lv1_0 == tmp_139_reg_1206) & ~(ap_const_lv1_0 == ap_reg_ppstg_tmp_98_reg_1237_pp0_it4) & ~(ap_reg_ppstg_locy_2_t_reg_1305_pp0_it4 == ap_const_lv2_1) & ~(ap_reg_ppstg_locy_2_t_reg_1305_pp0_it4 == ap_const_lv2_0)) | (~(ap_const_lv1_0 == brmerge_reg_1233) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it5) & ~((ap_sig_bdd_125 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4)) | (ap_sig_bdd_141 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it8))) & ~(ap_const_lv1_0 == ap_reg_ppstg_tmp_98_reg_1237_pp0_it4) & (ap_const_lv1_0 == ap_reg_ppstg_or_cond2_reg_1254_pp0_it4) & ~(ap_const_lv1_0 == ap_reg_ppstg_tmp_145_reg_1258_pp0_it4)) | (~(ap_const_lv1_0 == brmerge_reg_1233) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it5) & ~((ap_sig_bdd_125 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4)) | (ap_sig_bdd_141 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it8))) & ~(ap_const_lv1_0 == ap_reg_ppstg_tmp_98_reg_1237_pp0_it4) & ~(ap_const_lv1_0 == ap_reg_ppstg_or_cond2_reg_1254_pp0_it4)))) begin
        src_kernel_win_0_val_2_1_fu_120 <= src_kernel_win_0_val_2_0_reg_1328;
    end else if (((ap_const_lv1_0 == brmerge_reg_1233) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it5) & ~((ap_sig_bdd_125 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4)) | (ap_sig_bdd_141 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it8))) & (ap_const_lv1_0 == tmp_139_reg_1206) & ~(ap_const_lv1_0 == ap_reg_ppstg_tmp_98_reg_1237_pp0_it4) & (ap_reg_ppstg_locy_2_t_reg_1305_pp0_it4 == ap_const_lv2_0))) begin
        src_kernel_win_0_val_2_1_fu_120 <= col_buf_0_val_0_0_fu_180;
    end else if (((ap_const_lv1_0 == brmerge_reg_1233) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it5) & ~((ap_sig_bdd_125 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4)) | (ap_sig_bdd_141 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it8))) & (ap_const_lv1_0 == tmp_139_reg_1206) & ~(ap_const_lv1_0 == ap_reg_ppstg_tmp_98_reg_1237_pp0_it4) & (ap_reg_ppstg_locy_2_t_reg_1305_pp0_it4 == ap_const_lv2_1))) begin
        src_kernel_win_0_val_2_1_fu_120 <= right_border_buf_0_val_1_0_reg_1320;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & ~(tmp_95_fu_403_p2 == ap_const_lv1_0))) begin
        ImagLoc_y_cast_reg_1201 <= ImagLoc_y_cast_fu_426_p1;
        brmerge_reg_1233 <= brmerge_fu_506_p2;
        tmp_139_reg_1206 <= ImagLoc_y_fu_420_p2[ap_const_lv32_B];
        tmp_140_reg_1210 <= tmp_140_fu_478_p1;
        tmp_141_reg_1221 <= tmp_141_fu_492_p1;
        tmp_96_reg_1196 <= tmp_96_fu_414_p2;
        y_1_1_cast_reg_1228 <= y_1_1_cast_fu_502_p1;
        y_1_cast_reg_1216 <= y_1_cast_fu_488_p1;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (~((ap_sig_bdd_125 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4)) | (ap_sig_bdd_141 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it8)))) begin
        ap_reg_ppstg_col_assign_2_reg_1309_pp0_it4 <= col_assign_2_reg_1309;
        ap_reg_ppstg_col_assign_reg_1266_pp0_it2 <= ap_reg_ppstg_col_assign_reg_1266_pp0_it1;
        ap_reg_ppstg_col_assign_reg_1266_pp0_it3 <= ap_reg_ppstg_col_assign_reg_1266_pp0_it2;
        ap_reg_ppstg_locy_2_t_reg_1305_pp0_it4 <= locy_2_t_reg_1305;
        ap_reg_ppstg_or_cond221_i_i_reg_1246_pp0_it2 <= ap_reg_ppstg_or_cond221_i_i_reg_1246_pp0_it1;
        ap_reg_ppstg_or_cond221_i_i_reg_1246_pp0_it3 <= ap_reg_ppstg_or_cond221_i_i_reg_1246_pp0_it2;
        ap_reg_ppstg_or_cond221_i_i_reg_1246_pp0_it4 <= ap_reg_ppstg_or_cond221_i_i_reg_1246_pp0_it3;
        ap_reg_ppstg_or_cond221_i_i_reg_1246_pp0_it5 <= ap_reg_ppstg_or_cond221_i_i_reg_1246_pp0_it4;
        ap_reg_ppstg_or_cond221_i_i_reg_1246_pp0_it6 <= ap_reg_ppstg_or_cond221_i_i_reg_1246_pp0_it5;
        ap_reg_ppstg_or_cond221_i_i_reg_1246_pp0_it7 <= ap_reg_ppstg_or_cond221_i_i_reg_1246_pp0_it6;
        ap_reg_ppstg_or_cond2_reg_1254_pp0_it2 <= ap_reg_ppstg_or_cond2_reg_1254_pp0_it1;
        ap_reg_ppstg_or_cond2_reg_1254_pp0_it3 <= ap_reg_ppstg_or_cond2_reg_1254_pp0_it2;
        ap_reg_ppstg_or_cond2_reg_1254_pp0_it4 <= ap_reg_ppstg_or_cond2_reg_1254_pp0_it3;
        ap_reg_ppstg_src_kernel_win_0_val_0_1_24_reg_1347_pp0_it6 <= src_kernel_win_0_val_0_1_24_reg_1347;
        ap_reg_ppstg_src_kernel_win_0_val_0_1_24_reg_1347_pp0_it7 <= ap_reg_ppstg_src_kernel_win_0_val_0_1_24_reg_1347_pp0_it6;
        ap_reg_ppstg_src_kernel_win_0_val_0_1_lo_reg_1367_pp0_it7 <= src_kernel_win_0_val_0_1_lo_reg_1367;
        ap_reg_ppstg_src_kernel_win_0_val_1_1_24_reg_1354_pp0_it6 <= src_kernel_win_0_val_1_1_24_reg_1354;
        ap_reg_ppstg_tmp_106_reg_1250_pp0_it2 <= ap_reg_ppstg_tmp_106_reg_1250_pp0_it1;
        ap_reg_ppstg_tmp_106_reg_1250_pp0_it3 <= ap_reg_ppstg_tmp_106_reg_1250_pp0_it2;
        ap_reg_ppstg_tmp_106_reg_1250_pp0_it4 <= ap_reg_ppstg_tmp_106_reg_1250_pp0_it3;
        ap_reg_ppstg_tmp_107_reg_1262_pp0_it2 <= ap_reg_ppstg_tmp_107_reg_1262_pp0_it1;
        ap_reg_ppstg_tmp_107_reg_1262_pp0_it3 <= ap_reg_ppstg_tmp_107_reg_1262_pp0_it2;
        ap_reg_ppstg_tmp_145_reg_1258_pp0_it2 <= ap_reg_ppstg_tmp_145_reg_1258_pp0_it1;
        ap_reg_ppstg_tmp_145_reg_1258_pp0_it3 <= ap_reg_ppstg_tmp_145_reg_1258_pp0_it2;
        ap_reg_ppstg_tmp_145_reg_1258_pp0_it4 <= ap_reg_ppstg_tmp_145_reg_1258_pp0_it3;
        ap_reg_ppstg_tmp_98_reg_1237_pp0_it2 <= ap_reg_ppstg_tmp_98_reg_1237_pp0_it1;
        ap_reg_ppstg_tmp_98_reg_1237_pp0_it3 <= ap_reg_ppstg_tmp_98_reg_1237_pp0_it2;
        ap_reg_ppstg_tmp_98_reg_1237_pp0_it4 <= ap_reg_ppstg_tmp_98_reg_1237_pp0_it3;
        ap_reg_ppstg_tmp_98_reg_1237_pp0_it5 <= ap_reg_ppstg_tmp_98_reg_1237_pp0_it4;
        ap_reg_ppstg_tmp_98_reg_1237_pp0_it6 <= ap_reg_ppstg_tmp_98_reg_1237_pp0_it5;
        src_kernel_win_0_val_0_1_24_reg_1347 <= src_kernel_win_0_val_0_1_fu_108;
        src_kernel_win_0_val_1_1_24_reg_1354 <= src_kernel_win_0_val_1_1_fu_124;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & ~((ap_sig_bdd_125 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4)) | (ap_sig_bdd_141 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it8))))) begin
        ap_reg_ppstg_col_assign_reg_1266_pp0_it1 <= col_assign_reg_1266;
        ap_reg_ppstg_or_cond221_i_i_reg_1246_pp0_it1 <= or_cond221_i_i_reg_1246;
        ap_reg_ppstg_or_cond2_reg_1254_pp0_it1 <= or_cond2_reg_1254;
        ap_reg_ppstg_tmp_106_reg_1250_pp0_it1 <= tmp_106_reg_1250;
        ap_reg_ppstg_tmp_107_reg_1262_pp0_it1 <= tmp_107_reg_1262;
        ap_reg_ppstg_tmp_145_reg_1258_pp0_it1 <= tmp_145_reg_1258;
        ap_reg_ppstg_tmp_98_reg_1237_pp0_it1 <= tmp_98_reg_1237;
        tmp_98_reg_1237 <= tmp_98_fu_516_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((~(ap_const_lv1_0 == brmerge_reg_1233) & ~((ap_sig_bdd_125 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4)) | (ap_sig_bdd_141 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it8))) & ~(ap_const_lv1_0 == ap_reg_ppstg_tmp_98_reg_1237_pp0_it2) & (ap_const_lv1_0 == ap_reg_ppstg_or_cond2_reg_1254_pp0_it2) & (ap_const_lv1_0 == ap_reg_ppstg_tmp_145_reg_1258_pp0_it2) & (ap_const_lv1_0 == ap_reg_ppstg_tmp_106_reg_1250_pp0_it2))) begin
        col_assign_2_reg_1309 <= col_assign_2_fu_620_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & ~(ap_const_lv1_0 == brmerge_reg_1233) & ~((ap_sig_bdd_125 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4)) | (ap_sig_bdd_141 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it8))) & ~(ap_const_lv1_0 == tmp_98_fu_516_p2) & ~(ap_const_lv1_0 == or_cond2_fu_574_p2) & (ap_const_lv1_0 == tmp_107_fu_588_p2))) begin
        col_assign_reg_1266 <= col_assign_fu_593_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((~(ap_const_lv1_0 == ap_reg_ppstg_tmp_98_reg_1237_pp0_it3) & ~(ap_const_lv1_0 == brmerge_reg_1233) & ~(ap_const_lv1_0 == ap_reg_ppstg_or_cond2_reg_1254_pp0_it3) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4) & ~((ap_sig_bdd_125 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4)) | (ap_sig_bdd_141 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it8))) & (ap_const_lv1_0 == ap_reg_ppstg_tmp_107_reg_1262_pp0_it3) & ~(ap_reg_ppstg_col_assign_reg_1266_pp0_it3 == ap_const_lv2_1) & ~(ap_reg_ppstg_col_assign_reg_1266_pp0_it3 == ap_const_lv2_0))) begin
        col_buf_0_val_0_0_39_fu_116 <= k_buf_0_val_0_q0;
        right_border_buf_0_val_0_2_fu_176 <= k_buf_0_val_2_q0;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((~(ap_const_lv1_0 == ap_reg_ppstg_tmp_98_reg_1237_pp0_it3) & ~(ap_const_lv1_0 == brmerge_reg_1233) & ~(ap_const_lv1_0 == ap_reg_ppstg_or_cond2_reg_1254_pp0_it3) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4) & ~((ap_sig_bdd_125 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4)) | (ap_sig_bdd_141 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it8))) & (ap_const_lv1_0 == ap_reg_ppstg_tmp_107_reg_1262_pp0_it3) & (ap_reg_ppstg_col_assign_reg_1266_pp0_it3 == ap_const_lv2_1))) begin
        col_buf_0_val_0_0_40_fu_132 <= k_buf_0_val_0_q0;
        right_border_buf_0_val_0_1_fu_172 <= k_buf_0_val_2_q0;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((~(ap_const_lv1_0 == ap_reg_ppstg_tmp_98_reg_1237_pp0_it3) & ~(ap_const_lv1_0 == brmerge_reg_1233) & ~(ap_const_lv1_0 == ap_reg_ppstg_or_cond2_reg_1254_pp0_it3) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4) & ~((ap_sig_bdd_125 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4)) | (ap_sig_bdd_141 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it8))) & (ap_const_lv1_0 == ap_reg_ppstg_tmp_107_reg_1262_pp0_it3) & (ap_reg_ppstg_col_assign_reg_1266_pp0_it3 == ap_const_lv2_0))) begin
        col_buf_0_val_0_0_41_fu_140 <= k_buf_0_val_0_q0;
        right_border_buf_0_val_0_0_fu_168 <= k_buf_0_val_2_q0;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((~(ap_const_lv1_0 == ap_reg_ppstg_tmp_98_reg_1237_pp0_it3) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4) & ~((ap_sig_bdd_125 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4)) | (ap_sig_bdd_141 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it8))))) begin
        col_buf_0_val_0_0_fu_180 <= k_buf_0_val_0_q0;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & ~ap_sig_bdd_47)) begin
        heightloop_reg_1156 <= heightloop_fu_357_p2;
        p_neg228_i_i_cast_reg_1171 <= p_neg228_i_i_cast_fu_383_p2;
        ref_cast_reg_1182[0] <= ref_cast_fu_395_p1[0];
ref_cast_reg_1182[1] <= ref_cast_fu_395_p1[1];
ref_cast_reg_1182[2] <= ref_cast_fu_395_p1[2];
ref_cast_reg_1182[3] <= ref_cast_fu_395_p1[3];
ref_cast_reg_1182[4] <= ref_cast_fu_395_p1[4];
ref_cast_reg_1182[5] <= ref_cast_fu_395_p1[5];
ref_cast_reg_1182[6] <= ref_cast_fu_395_p1[6];
ref_cast_reg_1182[7] <= ref_cast_fu_395_p1[7];
ref_cast_reg_1182[8] <= ref_cast_fu_395_p1[8];
ref_cast_reg_1182[9] <= ref_cast_fu_395_p1[9];
ref_cast_reg_1182[10] <= ref_cast_fu_395_p1[10];
        ref_reg_1177 <= ref_fu_389_p2;
        tmp_93_cast_reg_1166[0] <= tmp_93_cast_fu_375_p1[0];
tmp_93_cast_reg_1166[1] <= tmp_93_cast_fu_375_p1[1];
tmp_93_cast_reg_1166[2] <= tmp_93_cast_fu_375_p1[2];
tmp_93_cast_reg_1166[3] <= tmp_93_cast_fu_375_p1[3];
tmp_93_cast_reg_1166[4] <= tmp_93_cast_fu_375_p1[4];
tmp_93_cast_reg_1166[5] <= tmp_93_cast_fu_375_p1[5];
tmp_93_cast_reg_1166[6] <= tmp_93_cast_fu_375_p1[6];
tmp_93_cast_reg_1166[7] <= tmp_93_cast_fu_375_p1[7];
tmp_93_cast_reg_1166[8] <= tmp_93_cast_fu_375_p1[8];
tmp_93_cast_reg_1166[9] <= tmp_93_cast_fu_375_p1[9];
tmp_93_cast_reg_1166[10] <= tmp_93_cast_fu_375_p1[10];
        widthloop_reg_1161 <= widthloop_fu_363_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1)) begin
        i_V_reg_1191 <= i_V_fu_408_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((~((ap_sig_bdd_125 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4)) | (ap_sig_bdd_141 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it8))) & ~(ap_const_lv1_0 == ap_reg_ppstg_tmp_98_reg_1237_pp0_it2))) begin
        k_buf_0_val_0_addr_reg_1287 <= tmp_s_fu_609_p1;
        k_buf_0_val_1_addr_reg_1293 <= tmp_s_fu_609_p1;
        k_buf_0_val_2_addr_reg_1299 <= tmp_s_fu_609_p1;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_lv1_0 == brmerge_reg_1233) & ~((ap_sig_bdd_125 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4)) | (ap_sig_bdd_141 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it8))) & (ap_const_lv1_0 == tmp_139_reg_1206) & ~(ap_const_lv1_0 == ap_reg_ppstg_tmp_98_reg_1237_pp0_it2))) begin
        locy_2_t_reg_1305 <= locy_2_t_fu_616_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & ~((ap_sig_bdd_125 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4)) | (ap_sig_bdd_141 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it8))) & ~(ap_const_lv1_0 == tmp_98_fu_516_p2))) begin
        or_cond221_i_i_reg_1246 <= or_cond221_i_i_fu_543_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & ~(ap_const_lv1_0 == brmerge_reg_1233) & ~((ap_sig_bdd_125 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4)) | (ap_sig_bdd_141 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it8))) & ~(ap_const_lv1_0 == tmp_98_fu_516_p2))) begin
        or_cond2_reg_1254 <= or_cond2_fu_574_p2;
        tmp_106_reg_1250 <= tmp_106_fu_569_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((~(ap_const_lv1_0 == ap_reg_ppstg_tmp_98_reg_1237_pp0_it3) & ~((ap_sig_bdd_125 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4)) | (ap_sig_bdd_141 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it8))))) begin
        right_border_buf_0_val_1_0_reg_1320 <= k_buf_0_val_1_q0;
        right_border_buf_0_val_2_0_reg_1315 <= k_buf_0_val_0_q0;
        src_kernel_win_0_val_2_0_reg_1328 <= k_buf_0_val_2_q0;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((~(ap_const_lv1_0 == ap_reg_ppstg_tmp_98_reg_1237_pp0_it3) & ~(ap_const_lv1_0 == brmerge_reg_1233) & ~(ap_const_lv1_0 == ap_reg_ppstg_or_cond2_reg_1254_pp0_it3) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4) & ~((ap_sig_bdd_125 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4)) | (ap_sig_bdd_141 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it8))) & (ap_const_lv1_0 == ap_reg_ppstg_tmp_107_reg_1262_pp0_it3) & ~(ap_reg_ppstg_col_assign_reg_1266_pp0_it3 == ap_const_lv2_1) & ~(ap_reg_ppstg_col_assign_reg_1266_pp0_it3 == ap_const_lv2_0)) | (~(ap_const_lv1_0 == ap_reg_ppstg_tmp_98_reg_1237_pp0_it3) & ~(ap_const_lv1_0 == brmerge_reg_1233) & ~(ap_const_lv1_0 == ap_reg_ppstg_or_cond2_reg_1254_pp0_it3) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4) & ~((ap_sig_bdd_125 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4)) | (ap_sig_bdd_141 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it8))) & (ap_const_lv1_0 == ap_reg_ppstg_tmp_107_reg_1262_pp0_it3) & (ap_reg_ppstg_col_assign_reg_1266_pp0_it3 == ap_const_lv2_1)) | (~(ap_const_lv1_0 == ap_reg_ppstg_tmp_98_reg_1237_pp0_it3) & ~(ap_const_lv1_0 == brmerge_reg_1233) & ~(ap_const_lv1_0 == ap_reg_ppstg_or_cond2_reg_1254_pp0_it3) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4) & ~((ap_sig_bdd_125 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4)) | (ap_sig_bdd_141 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it8))) & (ap_const_lv1_0 == ap_reg_ppstg_tmp_107_reg_1262_pp0_it3) & (ap_reg_ppstg_col_assign_reg_1266_pp0_it3 == ap_const_lv2_0)))) begin
        right_border_buf_0_val_1_2_14_fu_144 <= right_border_buf_0_val_1_2_19_fu_705_p3;
        right_border_buf_0_val_1_2_15_fu_148 <= right_border_buf_0_val_1_2_5_fu_696_p3;
        right_border_buf_0_val_1_2_16_fu_152 <= right_border_buf_0_val_1_2_3_fu_679_p3;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((~((ap_sig_bdd_125 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4)) | (ap_sig_bdd_141 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it8))) & ~(ap_const_lv1_0 == ap_reg_ppstg_or_cond221_i_i_reg_1246_pp0_it5))) begin
        src_kernel_win_0_val_0_1_lo_reg_1367 <= src_kernel_win_0_val_0_1_fu_108;
        src_kernel_win_0_val_1_1_lo_reg_1373 <= src_kernel_win_0_val_1_1_fu_124;
        temp_0_i_i_i_057_i_i_1_1_reg_1379 <= temp_0_i_i_i_057_i_i_1_1_fu_952_p3;
        tmp_192_1_1_reg_1384 <= tmp_192_1_1_fu_960_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_reg_ppiten_pp0_it7) & ~((ap_sig_bdd_125 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4)) | (ap_sig_bdd_141 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it8))) & ~(ap_const_lv1_0 == ap_reg_ppstg_tmp_98_reg_1237_pp0_it6))) begin
        src_kernel_win_0_val_0_2_fu_112 <= ap_reg_ppstg_src_kernel_win_0_val_0_1_24_reg_1347_pp0_it6;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_reg_ppiten_pp0_it6) & ~((ap_sig_bdd_125 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4)) | (ap_sig_bdd_141 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it8))) & ~(ap_const_lv1_0 == ap_reg_ppstg_tmp_98_reg_1237_pp0_it5))) begin
        src_kernel_win_0_val_1_2_fu_128 <= src_kernel_win_0_val_1_1_24_reg_1354;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_reg_ppiten_pp0_it5) & ~((ap_sig_bdd_125 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4)) | (ap_sig_bdd_141 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it8))) & ~(ap_const_lv1_0 == ap_reg_ppstg_tmp_98_reg_1237_pp0_it4))) begin
        src_kernel_win_0_val_2_2_fu_136 <= src_kernel_win_0_val_2_1_fu_120;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((~((ap_sig_bdd_125 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4)) | (ap_sig_bdd_141 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it8))) & ~(ap_const_lv1_0 == ap_reg_ppstg_tmp_98_reg_1237_pp0_it4) & ~(ap_const_lv1_0 == ap_reg_ppstg_or_cond221_i_i_reg_1246_pp0_it4))) begin
        temp_0_i_i_i_057_i_i_1_0_1_reg_1361 <= temp_0_i_i_i_057_i_i_1_0_1_fu_909_p3;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((~((ap_sig_bdd_125 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4)) | (ap_sig_bdd_141 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it8))) & ~(ap_const_lv1_0 == ap_reg_ppstg_or_cond221_i_i_reg_1246_pp0_it6))) begin
        temp_0_i_i_i_057_i_i_1_2_reg_1389 <= temp_0_i_i_i_057_i_i_1_2_fu_995_p3;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & ~(ap_const_lv1_0 == brmerge_reg_1233) & ~((ap_sig_bdd_125 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4)) | (ap_sig_bdd_141 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it8))) & ~(ap_const_lv1_0 == tmp_98_fu_516_p2) & ~(ap_const_lv1_0 == or_cond2_fu_574_p2))) begin
        tmp_107_reg_1262 <= tmp_107_fu_588_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((~((ap_sig_bdd_125 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4)) | (ap_sig_bdd_141 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it8))) & ~(ap_const_lv1_0 == ap_reg_ppstg_tmp_98_reg_1237_pp0_it1))) begin
        tmp_144_reg_1277 <= tmp_144_fu_598_p1;
        x_reg_1272 <= grp_toThreshold_borderInterpolate_fu_277_ap_return;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & ~(ap_const_lv1_0 == brmerge_reg_1233) & ~((ap_sig_bdd_125 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4)) | (ap_sig_bdd_141 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it8))) & ~(ap_const_lv1_0 == tmp_98_fu_516_p2) & (ap_const_lv1_0 == or_cond2_fu_574_p2))) begin
        tmp_145_reg_1258 <= ImagLoc_x_fu_548_p2[ap_const_lv32_B];
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((~(ap_const_lv1_0 == ap_reg_ppstg_tmp_98_reg_1237_pp0_it3) & (ap_const_lv1_0 == brmerge_reg_1233) & ~((ap_sig_bdd_125 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4)) | (ap_sig_bdd_141 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it8))) & (ap_const_lv1_0 == tmp_139_reg_1206))) begin
        tmp_146_reg_1335 <= tmp_146_fu_629_p1;
        tmp_147_reg_1341 <= tmp_147_fu_633_p1;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_lv1_0 == brmerge_reg_1233) & ~((ap_sig_bdd_125 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4)) | (ap_sig_bdd_141 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it8))) & ~(ap_const_lv1_0 == ap_reg_ppstg_tmp_98_reg_1237_pp0_it1) & (ap_const_lv1_0 == tmp_139_reg_1206))) begin
        tmp_148_reg_1282 <= tmp_148_fu_602_p1;
    end
end

/// ap_done assign process. ///
always @ (ap_done_reg or tmp_95_fu_403_p2 or ap_sig_cseq_ST_st2_fsm_1)
begin
    if (((ap_const_logic_1 == ap_done_reg) | ((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & (tmp_95_fu_403_p2 == ap_const_lv1_0)))) begin
        ap_done = ap_const_logic_1;
    end else begin
        ap_done = ap_const_logic_0;
    end
end

/// ap_idle assign process. ///
always @ (ap_start or ap_sig_cseq_ST_st1_fsm_0)
begin
    if ((~(ap_const_logic_1 == ap_start) & (ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0))) begin
        ap_idle = ap_const_logic_1;
    end else begin
        ap_idle = ap_const_logic_0;
    end
end

/// ap_ready assign process. ///
always @ (tmp_95_fu_403_p2 or ap_sig_cseq_ST_st2_fsm_1)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & (tmp_95_fu_403_p2 == ap_const_lv1_0))) begin
        ap_ready = ap_const_logic_1;
    end else begin
        ap_ready = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_pp0_stg0_fsm_2 assign process. ///
always @ (ap_sig_bdd_102)
begin
    if (ap_sig_bdd_102) begin
        ap_sig_cseq_ST_pp0_stg0_fsm_2 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_pp0_stg0_fsm_2 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st12_fsm_3 assign process. ///
always @ (ap_sig_bdd_384)
begin
    if (ap_sig_bdd_384) begin
        ap_sig_cseq_ST_st12_fsm_3 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st12_fsm_3 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st1_fsm_0 assign process. ///
always @ (ap_sig_bdd_23)
begin
    if (ap_sig_bdd_23) begin
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st2_fsm_1 assign process. ///
always @ (ap_sig_bdd_71)
begin
    if (ap_sig_bdd_71) begin
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_0;
    end
end

/// grp_toThreshold_borderInterpolate_fu_277_ap_ce assign process. ///
always @ (tmp_98_fu_516_p2 or tmp_98_reg_1237 or ap_sig_cseq_ST_pp0_stg0_fsm_2 or ap_sig_bdd_125 or ap_reg_ppiten_pp0_it4 or ap_sig_bdd_141 or ap_reg_ppiten_pp0_it8 or ap_reg_ppstg_tmp_98_reg_1237_pp0_it1)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & ~((ap_sig_bdd_125 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4)) | (ap_sig_bdd_141 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it8))) & (~(ap_const_lv1_0 == tmp_98_fu_516_p2) | ~(ap_const_lv1_0 == ap_reg_ppstg_tmp_98_reg_1237_pp0_it1) | ~(ap_const_lv1_0 == tmp_98_reg_1237)))) begin
        grp_toThreshold_borderInterpolate_fu_277_ap_ce = ap_const_logic_1;
    end else begin
        grp_toThreshold_borderInterpolate_fu_277_ap_ce = ap_const_logic_0;
    end
end

/// grp_toThreshold_borderInterpolate_fu_285_ap_ce assign process. ///
always @ (tmp_139_reg_1206 or brmerge_reg_1233 or tmp_98_fu_516_p2 or tmp_98_reg_1237 or ap_sig_cseq_ST_pp0_stg0_fsm_2 or ap_sig_bdd_125 or ap_reg_ppiten_pp0_it4 or ap_sig_bdd_141 or ap_reg_ppiten_pp0_it8 or ap_reg_ppstg_tmp_98_reg_1237_pp0_it1)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & ~((ap_sig_bdd_125 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4)) | (ap_sig_bdd_141 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it8))) & (((ap_const_lv1_0 == brmerge_reg_1233) & ~(ap_const_lv1_0 == ap_reg_ppstg_tmp_98_reg_1237_pp0_it1) & (ap_const_lv1_0 == tmp_139_reg_1206)) | ((ap_const_lv1_0 == brmerge_reg_1233) & ~(ap_const_lv1_0 == tmp_98_fu_516_p2) & (ap_const_lv1_0 == tmp_139_reg_1206)) | ((ap_const_lv1_0 == brmerge_reg_1233) & (ap_const_lv1_0 == tmp_139_reg_1206) & ~(ap_const_lv1_0 == tmp_98_reg_1237))))) begin
        grp_toThreshold_borderInterpolate_fu_285_ap_ce = ap_const_logic_1;
    end else begin
        grp_toThreshold_borderInterpolate_fu_285_ap_ce = ap_const_logic_0;
    end
end

/// grp_toThreshold_borderInterpolate_fu_293_ap_ce assign process. ///
always @ (tmp_139_reg_1206 or brmerge_reg_1233 or ap_sig_cseq_ST_pp0_stg0_fsm_2 or ap_reg_ppstg_tmp_98_reg_1237_pp0_it3 or ap_sig_bdd_125 or ap_reg_ppiten_pp0_it4 or ap_sig_bdd_141 or ap_reg_ppiten_pp0_it8 or ap_reg_ppstg_tmp_98_reg_1237_pp0_it1 or ap_reg_ppstg_tmp_98_reg_1237_pp0_it2)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & ~((ap_sig_bdd_125 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4)) | (ap_sig_bdd_141 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it8))) & (((ap_const_lv1_0 == brmerge_reg_1233) & ~(ap_const_lv1_0 == ap_reg_ppstg_tmp_98_reg_1237_pp0_it1) & (ap_const_lv1_0 == tmp_139_reg_1206)) | ((ap_const_lv1_0 == brmerge_reg_1233) & (ap_const_lv1_0 == tmp_139_reg_1206) & ~(ap_const_lv1_0 == ap_reg_ppstg_tmp_98_reg_1237_pp0_it2)) | (~(ap_const_lv1_0 == ap_reg_ppstg_tmp_98_reg_1237_pp0_it3) & (ap_const_lv1_0 == brmerge_reg_1233) & (ap_const_lv1_0 == tmp_139_reg_1206))))) begin
        grp_toThreshold_borderInterpolate_fu_293_ap_ce = ap_const_logic_1;
    end else begin
        grp_toThreshold_borderInterpolate_fu_293_ap_ce = ap_const_logic_0;
    end
end

/// grp_toThreshold_borderInterpolate_fu_301_ap_ce assign process. ///
always @ (tmp_139_reg_1206 or brmerge_reg_1233 or ap_sig_cseq_ST_pp0_stg0_fsm_2 or ap_reg_ppstg_tmp_98_reg_1237_pp0_it3 or ap_sig_bdd_125 or ap_reg_ppiten_pp0_it4 or ap_sig_bdd_141 or ap_reg_ppiten_pp0_it8 or ap_reg_ppstg_tmp_98_reg_1237_pp0_it1 or ap_reg_ppstg_tmp_98_reg_1237_pp0_it2)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & ~((ap_sig_bdd_125 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4)) | (ap_sig_bdd_141 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it8))) & (((ap_const_lv1_0 == brmerge_reg_1233) & ~(ap_const_lv1_0 == ap_reg_ppstg_tmp_98_reg_1237_pp0_it1) & (ap_const_lv1_0 == tmp_139_reg_1206)) | ((ap_const_lv1_0 == brmerge_reg_1233) & (ap_const_lv1_0 == tmp_139_reg_1206) & ~(ap_const_lv1_0 == ap_reg_ppstg_tmp_98_reg_1237_pp0_it2)) | (~(ap_const_lv1_0 == ap_reg_ppstg_tmp_98_reg_1237_pp0_it3) & (ap_const_lv1_0 == brmerge_reg_1233) & (ap_const_lv1_0 == tmp_139_reg_1206))))) begin
        grp_toThreshold_borderInterpolate_fu_301_ap_ce = ap_const_logic_1;
    end else begin
        grp_toThreshold_borderInterpolate_fu_301_ap_ce = ap_const_logic_0;
    end
end

/// k_buf_0_val_0_ce0 assign process. ///
always @ (ap_reg_ppiten_pp0_it3 or ap_sig_bdd_125 or ap_reg_ppiten_pp0_it4 or ap_sig_bdd_141 or ap_reg_ppiten_pp0_it8)
begin
    if (((ap_const_logic_1 == ap_reg_ppiten_pp0_it3) & ~((ap_sig_bdd_125 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4)) | (ap_sig_bdd_141 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it8))))) begin
        k_buf_0_val_0_ce0 = ap_const_logic_1;
    end else begin
        k_buf_0_val_0_ce0 = ap_const_logic_0;
    end
end

/// k_buf_0_val_0_ce1 assign process. ///
always @ (ap_sig_bdd_125 or ap_reg_ppiten_pp0_it4 or ap_sig_bdd_141 or ap_reg_ppiten_pp0_it8)
begin
    if (((ap_const_logic_1 == ap_reg_ppiten_pp0_it4) & ~((ap_sig_bdd_125 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4)) | (ap_sig_bdd_141 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it8))))) begin
        k_buf_0_val_0_ce1 = ap_const_logic_1;
    end else begin
        k_buf_0_val_0_ce1 = ap_const_logic_0;
    end
end

/// k_buf_0_val_0_we1 assign process. ///
always @ (brmerge_reg_1233 or ap_reg_ppstg_tmp_98_reg_1237_pp0_it3 or ap_reg_ppstg_or_cond2_reg_1254_pp0_it3 or ap_sig_bdd_125 or ap_reg_ppiten_pp0_it4 or ap_sig_bdd_141 or ap_reg_ppiten_pp0_it8)
begin
    if ((~(ap_const_lv1_0 == ap_reg_ppstg_tmp_98_reg_1237_pp0_it3) & ~(ap_const_lv1_0 == brmerge_reg_1233) & ~(ap_const_lv1_0 == ap_reg_ppstg_or_cond2_reg_1254_pp0_it3) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4) & ~((ap_sig_bdd_125 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4)) | (ap_sig_bdd_141 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it8))))) begin
        k_buf_0_val_0_we1 = ap_const_logic_1;
    end else begin
        k_buf_0_val_0_we1 = ap_const_logic_0;
    end
end

/// k_buf_0_val_1_ce0 assign process. ///
always @ (ap_reg_ppiten_pp0_it3 or ap_sig_bdd_125 or ap_reg_ppiten_pp0_it4 or ap_sig_bdd_141 or ap_reg_ppiten_pp0_it8)
begin
    if (((ap_const_logic_1 == ap_reg_ppiten_pp0_it3) & ~((ap_sig_bdd_125 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4)) | (ap_sig_bdd_141 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it8))))) begin
        k_buf_0_val_1_ce0 = ap_const_logic_1;
    end else begin
        k_buf_0_val_1_ce0 = ap_const_logic_0;
    end
end

/// k_buf_0_val_1_ce1 assign process. ///
always @ (brmerge_reg_1233 or ap_reg_ppstg_tmp_98_reg_1237_pp0_it3 or ap_reg_ppstg_or_cond2_reg_1254_pp0_it3 or ap_sig_bdd_125 or ap_reg_ppiten_pp0_it4 or ap_sig_bdd_141 or ap_reg_ppiten_pp0_it8 or ap_reg_ppstg_tmp_107_reg_1262_pp0_it3)
begin
    if (((~(ap_const_lv1_0 == ap_reg_ppstg_tmp_98_reg_1237_pp0_it3) & ~(ap_const_lv1_0 == brmerge_reg_1233) & ~(ap_const_lv1_0 == ap_reg_ppstg_or_cond2_reg_1254_pp0_it3) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4) & ~((ap_sig_bdd_125 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4)) | (ap_sig_bdd_141 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it8))) & (ap_const_lv1_0 == ap_reg_ppstg_tmp_107_reg_1262_pp0_it3)) | (~(ap_const_lv1_0 == ap_reg_ppstg_tmp_98_reg_1237_pp0_it3) & ~(ap_const_lv1_0 == brmerge_reg_1233) & ~(ap_const_lv1_0 == ap_reg_ppstg_or_cond2_reg_1254_pp0_it3) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4) & ~((ap_sig_bdd_125 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4)) | (ap_sig_bdd_141 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it8))) & ~(ap_const_lv1_0 == ap_reg_ppstg_tmp_107_reg_1262_pp0_it3)))) begin
        k_buf_0_val_1_ce1 = ap_const_logic_1;
    end else begin
        k_buf_0_val_1_ce1 = ap_const_logic_0;
    end
end

/// k_buf_0_val_1_we1 assign process. ///
always @ (brmerge_reg_1233 or ap_reg_ppstg_tmp_98_reg_1237_pp0_it3 or ap_reg_ppstg_or_cond2_reg_1254_pp0_it3 or ap_sig_bdd_125 or ap_reg_ppiten_pp0_it4 or ap_sig_bdd_141 or ap_reg_ppiten_pp0_it8 or ap_reg_ppstg_tmp_107_reg_1262_pp0_it3)
begin
    if (((~(ap_const_lv1_0 == ap_reg_ppstg_tmp_98_reg_1237_pp0_it3) & ~(ap_const_lv1_0 == brmerge_reg_1233) & ~(ap_const_lv1_0 == ap_reg_ppstg_or_cond2_reg_1254_pp0_it3) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4) & ~((ap_sig_bdd_125 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4)) | (ap_sig_bdd_141 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it8))) & (ap_const_lv1_0 == ap_reg_ppstg_tmp_107_reg_1262_pp0_it3)) | (~(ap_const_lv1_0 == ap_reg_ppstg_tmp_98_reg_1237_pp0_it3) & ~(ap_const_lv1_0 == brmerge_reg_1233) & ~(ap_const_lv1_0 == ap_reg_ppstg_or_cond2_reg_1254_pp0_it3) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4) & ~((ap_sig_bdd_125 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4)) | (ap_sig_bdd_141 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it8))) & ~(ap_const_lv1_0 == ap_reg_ppstg_tmp_107_reg_1262_pp0_it3)))) begin
        k_buf_0_val_1_we1 = ap_const_logic_1;
    end else begin
        k_buf_0_val_1_we1 = ap_const_logic_0;
    end
end

/// k_buf_0_val_2_ce0 assign process. ///
always @ (ap_reg_ppiten_pp0_it3 or ap_sig_bdd_125 or ap_reg_ppiten_pp0_it4 or ap_sig_bdd_141 or ap_reg_ppiten_pp0_it8)
begin
    if (((ap_const_logic_1 == ap_reg_ppiten_pp0_it3) & ~((ap_sig_bdd_125 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4)) | (ap_sig_bdd_141 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it8))))) begin
        k_buf_0_val_2_ce0 = ap_const_logic_1;
    end else begin
        k_buf_0_val_2_ce0 = ap_const_logic_0;
    end
end

/// k_buf_0_val_2_ce1 assign process. ///
always @ (brmerge_reg_1233 or ap_reg_ppstg_tmp_98_reg_1237_pp0_it3 or ap_reg_ppstg_or_cond2_reg_1254_pp0_it3 or ap_sig_bdd_125 or ap_reg_ppiten_pp0_it4 or ap_sig_bdd_141 or ap_reg_ppiten_pp0_it8 or ap_reg_ppstg_tmp_107_reg_1262_pp0_it3)
begin
    if (((~(ap_const_lv1_0 == ap_reg_ppstg_tmp_98_reg_1237_pp0_it3) & ~(ap_const_lv1_0 == brmerge_reg_1233) & ~(ap_const_lv1_0 == ap_reg_ppstg_or_cond2_reg_1254_pp0_it3) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4) & ~((ap_sig_bdd_125 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4)) | (ap_sig_bdd_141 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it8))) & (ap_const_lv1_0 == ap_reg_ppstg_tmp_107_reg_1262_pp0_it3)) | (~(ap_const_lv1_0 == ap_reg_ppstg_tmp_98_reg_1237_pp0_it3) & ~(ap_const_lv1_0 == brmerge_reg_1233) & ~(ap_const_lv1_0 == ap_reg_ppstg_or_cond2_reg_1254_pp0_it3) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4) & ~((ap_sig_bdd_125 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4)) | (ap_sig_bdd_141 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it8))) & ~(ap_const_lv1_0 == ap_reg_ppstg_tmp_107_reg_1262_pp0_it3)))) begin
        k_buf_0_val_2_ce1 = ap_const_logic_1;
    end else begin
        k_buf_0_val_2_ce1 = ap_const_logic_0;
    end
end

/// k_buf_0_val_2_we1 assign process. ///
always @ (brmerge_reg_1233 or ap_reg_ppstg_tmp_98_reg_1237_pp0_it3 or ap_reg_ppstg_or_cond2_reg_1254_pp0_it3 or ap_sig_bdd_125 or ap_reg_ppiten_pp0_it4 or ap_sig_bdd_141 or ap_reg_ppiten_pp0_it8 or ap_reg_ppstg_tmp_107_reg_1262_pp0_it3)
begin
    if (((~(ap_const_lv1_0 == ap_reg_ppstg_tmp_98_reg_1237_pp0_it3) & ~(ap_const_lv1_0 == brmerge_reg_1233) & ~(ap_const_lv1_0 == ap_reg_ppstg_or_cond2_reg_1254_pp0_it3) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4) & ~((ap_sig_bdd_125 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4)) | (ap_sig_bdd_141 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it8))) & (ap_const_lv1_0 == ap_reg_ppstg_tmp_107_reg_1262_pp0_it3)) | (~(ap_const_lv1_0 == ap_reg_ppstg_tmp_98_reg_1237_pp0_it3) & ~(ap_const_lv1_0 == brmerge_reg_1233) & ~(ap_const_lv1_0 == ap_reg_ppstg_or_cond2_reg_1254_pp0_it3) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4) & ~((ap_sig_bdd_125 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4)) | (ap_sig_bdd_141 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it8))) & ~(ap_const_lv1_0 == ap_reg_ppstg_tmp_107_reg_1262_pp0_it3)))) begin
        k_buf_0_val_2_we1 = ap_const_logic_1;
    end else begin
        k_buf_0_val_2_we1 = ap_const_logic_0;
    end
end

/// p_dst_data_stream_V_write assign process. ///
always @ (ap_sig_bdd_125 or ap_reg_ppiten_pp0_it4 or ap_reg_ppstg_or_cond221_i_i_reg_1246_pp0_it7 or ap_sig_bdd_141 or ap_reg_ppiten_pp0_it8)
begin
    if ((~(ap_const_lv1_0 == ap_reg_ppstg_or_cond221_i_i_reg_1246_pp0_it7) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it8) & ~((ap_sig_bdd_125 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4)) | (ap_sig_bdd_141 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it8))))) begin
        p_dst_data_stream_V_write = ap_const_logic_1;
    end else begin
        p_dst_data_stream_V_write = ap_const_logic_0;
    end
end

/// p_src_data_stream_V_read assign process. ///
always @ (brmerge_reg_1233 or ap_reg_ppstg_tmp_98_reg_1237_pp0_it3 or ap_reg_ppstg_or_cond2_reg_1254_pp0_it3 or ap_sig_bdd_125 or ap_reg_ppiten_pp0_it4 or ap_sig_bdd_141 or ap_reg_ppiten_pp0_it8)
begin
    if ((~(ap_const_lv1_0 == ap_reg_ppstg_tmp_98_reg_1237_pp0_it3) & ~(ap_const_lv1_0 == brmerge_reg_1233) & ~(ap_const_lv1_0 == ap_reg_ppstg_or_cond2_reg_1254_pp0_it3) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4) & ~((ap_sig_bdd_125 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4)) | (ap_sig_bdd_141 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it8))))) begin
        p_src_data_stream_V_read = ap_const_logic_1;
    end else begin
        p_src_data_stream_V_read = ap_const_logic_0;
    end
end
/// the next state (ap_NS_fsm) of the state machine. ///
always @ (ap_CS_fsm or ap_sig_bdd_47 or tmp_95_fu_403_p2 or ap_sig_bdd_125 or ap_reg_ppiten_pp0_it4 or ap_reg_ppiten_pp0_it5 or ap_reg_ppiten_pp0_it6 or ap_reg_ppiten_pp0_it7 or ap_sig_bdd_141 or ap_reg_ppiten_pp0_it8)
begin
    case (ap_CS_fsm)
        ap_ST_st1_fsm_0 : 
        begin
            if (~ap_sig_bdd_47) begin
                ap_NS_fsm = ap_ST_st2_fsm_1;
            end else begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end
        end
        ap_ST_st2_fsm_1 : 
        begin
            if ((tmp_95_fu_403_p2 == ap_const_lv1_0)) begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end else begin
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_2;
            end
        end
        ap_ST_pp0_stg0_fsm_2 : 
        begin
            if ((~((ap_const_logic_1 == ap_reg_ppiten_pp0_it8) & ~((ap_sig_bdd_125 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4)) | (ap_sig_bdd_141 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it8))) & ~(ap_const_logic_1 == ap_reg_ppiten_pp0_it7)) & ~((ap_const_logic_1 == ap_reg_ppiten_pp0_it5) & ~((ap_sig_bdd_125 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4)) | (ap_sig_bdd_141 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it8))) & ~(ap_const_logic_1 == ap_reg_ppiten_pp0_it4) & ~(ap_const_logic_1 == ap_reg_ppiten_pp0_it6)))) begin
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_2;
            end else if ((((ap_const_logic_1 == ap_reg_ppiten_pp0_it8) & ~((ap_sig_bdd_125 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4)) | (ap_sig_bdd_141 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it8))) & ~(ap_const_logic_1 == ap_reg_ppiten_pp0_it7)) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it5) & ~((ap_sig_bdd_125 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4)) | (ap_sig_bdd_141 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it8))) & ~(ap_const_logic_1 == ap_reg_ppiten_pp0_it4) & ~(ap_const_logic_1 == ap_reg_ppiten_pp0_it6)))) begin
                ap_NS_fsm = ap_ST_st12_fsm_3;
            end else begin
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_2;
            end
        end
        ap_ST_st12_fsm_3 : 
        begin
            ap_NS_fsm = ap_ST_st2_fsm_1;
        end
        default : 
        begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ImagLoc_x_fu_548_p2 = ($signed(tmp_97_cast_fu_512_p1) + $signed(ap_const_lv12_FFF));
assign ImagLoc_y_cast_fu_426_p1 = $signed(ImagLoc_y_fu_420_p2);
assign ImagLoc_y_fu_420_p2 = ($signed(tmp_94_cast_cast3_fu_399_p1) + $signed(ap_const_lv12_FFC));

/// ap_sig_bdd_102 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_102 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_2]);
end

/// ap_sig_bdd_125 assign process. ///
always @ (p_src_data_stream_V_empty_n or brmerge_reg_1233 or ap_reg_ppstg_tmp_98_reg_1237_pp0_it3 or ap_reg_ppstg_or_cond2_reg_1254_pp0_it3)
begin
    ap_sig_bdd_125 = ((p_src_data_stream_V_empty_n == ap_const_logic_0) & ~(ap_const_lv1_0 == ap_reg_ppstg_tmp_98_reg_1237_pp0_it3) & ~(ap_const_lv1_0 == brmerge_reg_1233) & ~(ap_const_lv1_0 == ap_reg_ppstg_or_cond2_reg_1254_pp0_it3));
end

/// ap_sig_bdd_141 assign process. ///
always @ (p_dst_data_stream_V_full_n or ap_reg_ppstg_or_cond221_i_i_reg_1246_pp0_it7)
begin
    ap_sig_bdd_141 = ((p_dst_data_stream_V_full_n == ap_const_logic_0) & ~(ap_const_lv1_0 == ap_reg_ppstg_or_cond221_i_i_reg_1246_pp0_it7));
end

/// ap_sig_bdd_23 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_23 = (ap_CS_fsm[ap_const_lv32_0] == ap_const_lv1_1);
end

/// ap_sig_bdd_384 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_384 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_3]);
end

/// ap_sig_bdd_47 assign process. ///
always @ (ap_start or ap_done_reg)
begin
    ap_sig_bdd_47 = ((ap_start == ap_const_logic_0) | (ap_done_reg == ap_const_logic_1));
end

/// ap_sig_bdd_71 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_71 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_1]);
end
assign brmerge_fu_506_p2 = (tmp_102_fu_430_p2 | or_cond_fu_457_p2);
assign col_assign_2_fu_620_p2 = (tmp_144_reg_1277 + p_neg228_i_i_cast_reg_1171);
assign col_assign_fu_593_p2 = (tmp_143_fu_554_p1 + p_neg228_i_i_cast_reg_1171);
assign col_buf_0_val_0_0_42_fu_837_p3 = ((sel_tmp_fu_832_p2)? col_buf_0_val_0_0_40_fu_132: col_buf_0_val_0_0_39_fu_116);
assign col_buf_0_val_0_0_46_fu_850_p3 = ((sel_tmp2_fu_845_p2)? col_buf_0_val_0_0_41_fu_140: col_buf_0_val_0_0_42_fu_837_p3);
assign grp_toThreshold_borderInterpolate_fu_277_borderType = ap_const_lv4_1;
assign grp_toThreshold_borderInterpolate_fu_277_len = p_src_cols_V_read;
assign grp_toThreshold_borderInterpolate_fu_277_p = $signed(ImagLoc_x_fu_548_p2);
assign grp_toThreshold_borderInterpolate_fu_285_borderType = ap_const_lv4_1;
assign grp_toThreshold_borderInterpolate_fu_285_len = p_src_rows_V_read;
assign grp_toThreshold_borderInterpolate_fu_285_p = y_1_1_cast_reg_1228;
assign grp_toThreshold_borderInterpolate_fu_293_borderType = ap_const_lv4_1;
assign grp_toThreshold_borderInterpolate_fu_293_len = p_src_rows_V_read;
assign grp_toThreshold_borderInterpolate_fu_293_p = ImagLoc_y_cast_reg_1201;
assign grp_toThreshold_borderInterpolate_fu_301_borderType = ap_const_lv4_1;
assign grp_toThreshold_borderInterpolate_fu_301_len = p_src_rows_V_read;
assign grp_toThreshold_borderInterpolate_fu_301_p = y_1_cast_reg_1216;
assign heightloop_fu_357_p2 = (tmp_fu_349_p1 + ap_const_lv11_5);
assign i_V_fu_408_p2 = (p_012_0_i_i_reg_254 + ap_const_lv11_1);
assign icmp4_fu_537_p2 = (tmp_142_fu_527_p4 != ap_const_lv10_0? 1'b1: 1'b0);
assign icmp_fu_446_p2 = ($signed(tmp_138_fu_436_p4) > $signed(11'b00000000000)? 1'b1: 1'b0);
assign j_V_fu_521_p2 = (p_025_0_i_i_reg_265 + ap_const_lv11_1);
assign k_buf_0_val_0_address0 = tmp_s_fu_609_p1;
assign k_buf_0_val_0_address1 = k_buf_0_val_0_addr_reg_1287;
assign k_buf_0_val_0_d1 = p_src_data_stream_V_dout;
assign k_buf_0_val_1_address0 = tmp_s_fu_609_p1;
assign k_buf_0_val_1_address1 = k_buf_0_val_1_addr_reg_1293;
assign k_buf_0_val_1_d1 = k_buf_0_val_0_q0;
assign k_buf_0_val_2_address0 = tmp_s_fu_609_p1;
assign k_buf_0_val_2_address1 = k_buf_0_val_2_addr_reg_1299;
assign k_buf_0_val_2_d1 = k_buf_0_val_1_q0;
assign locy_1_t_fu_770_p2 = (tmp_141_reg_1221 - tmp_147_reg_1341);
assign locy_2_t_fu_616_p2 = (tmp_141_reg_1221 - tmp_148_reg_1282);
assign locy_fu_738_p2 = (tmp_140_reg_1210 - tmp_146_reg_1335);
assign or_cond221_i_i_fu_543_p2 = (tmp_96_reg_1196 & icmp4_fu_537_p2);
assign or_cond2_fu_574_p2 = (tmp_105_fu_563_p2 & tmp_106_fu_569_p2);
assign or_cond_fu_457_p2 = (icmp_fu_446_p2 & tmp_103_fu_452_p2);
assign p_dst_data_stream_V_din = ((tmp_192_2_2_fu_1017_p2)? ap_reg_ppstg_src_kernel_win_0_val_0_1_lo_reg_1367_pp0_it7: temp_0_i_i_i_057_i_i_1_2_1_fu_1011_p3);
assign p_i_i_fu_471_p3 = ((tmp_103_fu_452_p2)? ap_const_lv11_2: ref_reg_1177);
assign p_neg228_i_i_cast_fu_383_p2 = (tmp_137_fu_379_p1 ^ ap_const_lv2_3);
assign ref_cast_fu_395_p1 = ref_fu_389_p2;
assign ref_fu_389_p2 = ($signed(tmp_fu_349_p1) + $signed(ap_const_lv11_7FF));
assign right_border_buf_0_val_1_2_19_fu_705_p3 = ((sel_tmp18_fu_674_p2)? k_buf_0_val_1_q0: right_border_buf_0_val_1_2_14_fu_144);
assign right_border_buf_0_val_1_2_20_fu_867_p3 = ((sel_tmp2_fu_845_p2)? right_border_buf_0_val_1_2_14_fu_144: right_border_buf_0_val_1_2_fu_859_p3);
assign right_border_buf_0_val_1_2_2_fu_666_p3 = ((sel_tmp16_fu_661_p2)? right_border_buf_0_val_1_2_16_fu_152: k_buf_0_val_1_q0);
assign right_border_buf_0_val_1_2_3_fu_679_p3 = ((sel_tmp18_fu_674_p2)? right_border_buf_0_val_1_2_16_fu_152: right_border_buf_0_val_1_2_2_fu_666_p3);
assign right_border_buf_0_val_1_2_4_fu_688_p3 = ((sel_tmp16_fu_661_p2)? k_buf_0_val_1_q0: right_border_buf_0_val_1_2_15_fu_148);
assign right_border_buf_0_val_1_2_5_fu_696_p3 = ((sel_tmp18_fu_674_p2)? right_border_buf_0_val_1_2_15_fu_148: right_border_buf_0_val_1_2_4_fu_688_p3);
assign right_border_buf_0_val_1_2_fu_859_p3 = ((sel_tmp_fu_832_p2)? right_border_buf_0_val_1_2_15_fu_148: right_border_buf_0_val_1_2_16_fu_152);
assign sel_tmp10_fu_756_p2 = (locy_fu_738_p2 == ap_const_lv2_1? 1'b1: 1'b0);
assign sel_tmp12_fu_777_p2 = (tmp_141_reg_1221 == tmp_147_reg_1341? 1'b1: 1'b0);
assign sel_tmp13_fu_781_p3 = ((sel_tmp12_fu_777_p2)? col_buf_0_val_0_0_fu_180: src_kernel_win_0_val_2_0_reg_1328);
assign sel_tmp14_fu_788_p2 = (locy_1_t_fu_770_p2 == ap_const_lv2_1? 1'b1: 1'b0);
assign sel_tmp16_fu_661_p2 = (ap_reg_ppstg_col_assign_reg_1266_pp0_it3 == ap_const_lv2_1? 1'b1: 1'b0);
assign sel_tmp18_fu_674_p2 = (ap_reg_ppstg_col_assign_reg_1266_pp0_it3 == ap_const_lv2_0? 1'b1: 1'b0);
assign sel_tmp2_fu_845_p2 = (ap_reg_ppstg_col_assign_2_reg_1309_pp0_it4 == ap_const_lv2_0? 1'b1: 1'b0);
assign sel_tmp8_fu_745_p2 = (tmp_140_reg_1210 == tmp_146_reg_1335? 1'b1: 1'b0);
assign sel_tmp9_fu_749_p3 = ((sel_tmp8_fu_745_p2)? col_buf_0_val_0_0_fu_180: src_kernel_win_0_val_2_0_reg_1328);
assign sel_tmp_fu_832_p2 = (ap_reg_ppstg_col_assign_2_reg_1309_pp0_it4 == ap_const_lv2_1? 1'b1: 1'b0);
assign src_kernel_win_0_val_0_0_fu_762_p3 = ((sel_tmp10_fu_756_p2)? right_border_buf_0_val_1_0_reg_1320: sel_tmp9_fu_749_p3);
assign src_kernel_win_0_val_1_0_fu_794_p3 = ((sel_tmp14_fu_788_p2)? right_border_buf_0_val_1_0_reg_1320: sel_tmp13_fu_781_p3);
assign temp_0_i_i_i_057_i_i_1_0_1_fu_909_p3 = ((tmp_192_0_1_fu_903_p2)? src_kernel_win_0_val_2_1_fu_120: src_kernel_win_0_val_2_2_fu_136);
assign temp_0_i_i_i_057_i_i_1_0_2_fu_939_p3 = ((tmp_192_0_2_fu_934_p2)? src_kernel_win_0_val_2_1_fu_120: temp_0_i_i_i_057_i_i_1_0_1_reg_1361);
assign temp_0_i_i_i_057_i_i_1_1_1_fu_972_p3 = ((tmp_192_1_1_reg_1384)? ap_reg_ppstg_src_kernel_win_0_val_1_1_24_reg_1354_pp0_it6: temp_0_i_i_i_057_i_i_1_1_reg_1379);
assign temp_0_i_i_i_057_i_i_1_1_2_fu_982_p3 = ((tmp_192_1_2_fu_977_p2)? src_kernel_win_0_val_1_1_lo_reg_1373: temp_0_i_i_i_057_i_i_1_1_1_fu_972_p3);
assign temp_0_i_i_i_057_i_i_1_1_fu_952_p3 = ((tmp_192_1_fu_946_p2)? src_kernel_win_0_val_1_2_fu_128: temp_0_i_i_i_057_i_i_1_0_2_fu_939_p3);
assign temp_0_i_i_i_057_i_i_1_2_1_fu_1011_p3 = ((tmp_192_2_1_fu_1007_p2)? ap_reg_ppstg_src_kernel_win_0_val_0_1_24_reg_1347_pp0_it7: temp_0_i_i_i_057_i_i_1_2_reg_1389);
assign temp_0_i_i_i_057_i_i_1_2_fu_995_p3 = ((tmp_192_2_fu_989_p2)? src_kernel_win_0_val_0_2_fu_112: temp_0_i_i_i_057_i_i_1_1_2_fu_982_p3);
assign tmp_102_fu_430_p2 = ($signed(ImagLoc_y_fu_420_p2) < $signed(12'b111111111111)? 1'b1: 1'b0);
assign tmp_103_fu_452_p2 = ($signed(ImagLoc_y_fu_420_p2) < $signed(ref_cast_reg_1182)? 1'b1: 1'b0);
assign tmp_105_fu_563_p2 = (p_025_0_i_i_reg_265 != ap_const_lv11_0? 1'b1: 1'b0);
assign tmp_106_fu_569_p2 = ($signed(ImagLoc_x_fu_548_p2) < $signed(p_src_cols_V_read)? 1'b1: 1'b0);
assign tmp_107_fu_588_p2 = ($signed(ImagLoc_x_fu_548_p2) < $signed(tmp_93_cast_reg_1166)? 1'b1: 1'b0);
assign tmp_136_fu_353_p1 = p_src_cols_V_read[10:0];
assign tmp_137_fu_379_p1 = p_src_cols_V_read[1:0];
assign tmp_138_fu_436_p4 = {{ImagLoc_y_fu_420_p2[ap_const_lv32_B : ap_const_lv32_1]}};
assign tmp_140_fu_478_p1 = p_i_i_fu_471_p3[1:0];
assign tmp_141_fu_492_p1 = p_i_i_fu_471_p3[1:0];
assign tmp_142_fu_527_p4 = {{p_025_0_i_i_reg_265[ap_const_lv32_A : ap_const_lv32_1]}};
assign tmp_143_fu_554_p1 = ImagLoc_x_fu_548_p2[1:0];
assign tmp_144_fu_598_p1 = grp_toThreshold_borderInterpolate_fu_277_ap_return[1:0];
assign tmp_146_fu_629_p1 = grp_toThreshold_borderInterpolate_fu_293_ap_return[1:0];
assign tmp_147_fu_633_p1 = grp_toThreshold_borderInterpolate_fu_301_ap_return[1:0];
assign tmp_148_fu_602_p1 = grp_toThreshold_borderInterpolate_fu_285_ap_return[1:0];
assign tmp_192_0_1_fu_903_p2 = (src_kernel_win_0_val_2_1_fu_120 > src_kernel_win_0_val_2_2_fu_136? 1'b1: 1'b0);
assign tmp_192_0_2_fu_934_p2 = (src_kernel_win_0_val_2_1_fu_120 > temp_0_i_i_i_057_i_i_1_0_1_reg_1361? 1'b1: 1'b0);
assign tmp_192_1_1_fu_960_p2 = (src_kernel_win_0_val_1_1_24_reg_1354 > temp_0_i_i_i_057_i_i_1_1_fu_952_p3? 1'b1: 1'b0);
assign tmp_192_1_2_fu_977_p2 = (src_kernel_win_0_val_1_1_lo_reg_1373 > temp_0_i_i_i_057_i_i_1_1_1_fu_972_p3? 1'b1: 1'b0);
assign tmp_192_1_fu_946_p2 = (src_kernel_win_0_val_1_2_fu_128 > temp_0_i_i_i_057_i_i_1_0_2_fu_939_p3? 1'b1: 1'b0);
assign tmp_192_2_1_fu_1007_p2 = (ap_reg_ppstg_src_kernel_win_0_val_0_1_24_reg_1347_pp0_it7 > temp_0_i_i_i_057_i_i_1_2_reg_1389? 1'b1: 1'b0);
assign tmp_192_2_2_fu_1017_p2 = (ap_reg_ppstg_src_kernel_win_0_val_0_1_lo_reg_1367_pp0_it7 > temp_0_i_i_i_057_i_i_1_2_1_fu_1011_p3? 1'b1: 1'b0);
assign tmp_192_2_fu_989_p2 = (src_kernel_win_0_val_0_2_fu_112 > temp_0_i_i_i_057_i_i_1_1_2_fu_982_p3? 1'b1: 1'b0);
assign tmp_93_cast_fu_375_p1 = tmp_93_fu_369_p2;
assign tmp_93_fu_369_p2 = ($signed(tmp_136_fu_353_p1) + $signed(ap_const_lv11_7FD));
assign tmp_94_cast_cast3_fu_399_p1 = p_012_0_i_i_reg_254;
assign tmp_95_fu_403_p2 = (p_012_0_i_i_reg_254 < heightloop_reg_1156? 1'b1: 1'b0);
assign tmp_96_fu_414_p2 = (p_012_0_i_i_reg_254 > ap_const_lv11_4? 1'b1: 1'b0);
assign tmp_97_cast_fu_512_p1 = p_025_0_i_i_reg_265;
assign tmp_98_fu_516_p2 = (p_025_0_i_i_reg_265 < widthloop_reg_1161? 1'b1: 1'b0);
assign tmp_fu_349_p1 = p_src_rows_V_read[10:0];
assign tmp_s_fu_609_p1 = $unsigned(x_4_fu_606_p1);
assign widthloop_fu_363_p2 = (tmp_136_fu_353_p1 + ap_const_lv11_2);
assign x_4_fu_606_p1 = $signed(x_reg_1272);
assign y_1_1_cast_fu_502_p1 = $signed(y_1_1_fu_496_p2);
assign y_1_1_fu_496_p2 = ($signed(tmp_94_cast_cast3_fu_399_p1) + $signed(ap_const_lv12_FFA));
assign y_1_cast_fu_488_p1 = $signed(y_1_fu_482_p2);
assign y_1_fu_482_p2 = ($signed(tmp_94_cast_cast3_fu_399_p1) + $signed(ap_const_lv12_FFB));
always @ (posedge ap_clk)
begin
    tmp_93_cast_reg_1166[11] <= 1'b0;
    ref_cast_reg_1182[11] <= 1'b0;
end



endmodule //toThreshold_Dilate_0_0_1080_1920_1

