// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2014.4
// Copyright (C) 2014 Xilinx Inc. All rights reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module toThreshold_borderInterpolate (
        ap_clk,
        ap_rst,
        p,
        len,
        borderType,
        ap_return,
        ap_ce
);

parameter    ap_const_logic_1 = 1'b1;
parameter    ap_const_lv1_0 = 1'b0;
parameter    ap_const_lv32_C = 32'b1100;
parameter    ap_const_lv1_1 = 1'b1;
parameter    ap_const_lv4_1 = 4'b1;
parameter    ap_const_lv4_2 = 4'b10;
parameter    ap_const_lv4_4 = 4'b100;
parameter    ap_const_lv13_1FFF = 13'b1111111111111;
parameter    ap_const_lv4_0 = 4'b0000;
parameter    ap_const_lv13_0 = 13'b0000000000000;
parameter    ap_const_lv12_1 = 12'b1;
parameter    ap_const_lv14_3FFE = 14'b11111111111110;
parameter    ap_const_lv15_0 = 15'b000000000000000;
parameter    ap_const_logic_0 = 1'b0;

input   ap_clk;
input   ap_rst;
input  [12:0] p;
input  [11:0] len;
input  [3:0] borderType;
output  [14:0] ap_return;
input   ap_ce;

reg   [11:0] len_read_reg_406;
reg   [12:0] p_read_reg_412;
reg   [12:0] ap_reg_ppstg_p_read_reg_412_pp0_it1;
wire   [12:0] len_cast1_cast_fu_73_p1;
reg   [12:0] len_cast1_cast_reg_421;
wire   [0:0] or_cond_fu_83_p2;
reg   [0:0] or_cond_reg_428;
reg   [0:0] ap_reg_ppstg_or_cond_reg_428_pp0_it1;
wire   [0:0] tmp_2_fu_89_p2;
reg   [0:0] tmp_2_reg_434;
reg   [0:0] tmp_151_reg_440;
wire   [0:0] tmp_5_fu_103_p2;
reg   [0:0] tmp_5_reg_447;
wire   [0:0] tmp_7_fu_109_p2;
reg   [0:0] tmp_7_reg_453;
wire   [12:0] p_assign_1_fu_115_p2;
reg   [12:0] p_assign_1_reg_459;
wire   [0:0] tmp_11_fu_121_p2;
reg   [0:0] tmp_11_reg_464;
wire   [0:0] sel_tmp_fu_133_p2;
reg   [0:0] sel_tmp_reg_469;
wire   [12:0] p_p_fu_160_p3;
reg   [12:0] p_p_reg_474;
wire   [12:0] p_p3_fu_170_p3;
reg   [12:0] p_p3_reg_479;
wire   [12:0] p_p2_fu_212_p3;
reg   [12:0] p_p2_reg_484;
wire   [14:0] sel_tmp11_fu_294_p3;
reg   [14:0] sel_tmp11_reg_489;
wire   [0:0] sel_tmp18_demorgan_fu_307_p2;
reg   [0:0] sel_tmp18_demorgan_reg_494;
wire   [0:0] sel_tmp25_fu_312_p2;
reg   [0:0] sel_tmp25_reg_499;
wire   [0:0] sel_tmp33_fu_318_p2;
reg   [0:0] sel_tmp33_reg_504;
wire   [0:0] sel_tmp41_fu_335_p2;
reg   [0:0] sel_tmp41_reg_509;
wire   [0:0] sel_tmp51_fu_347_p2;
reg   [0:0] sel_tmp51_reg_514;
wire   [0:0] tmp_fu_59_p3;
wire   [0:0] tmp_1_fu_77_p2;
wire   [0:0] rev_fu_67_p2;
wire   [0:0] tmp_1_not_fu_127_p2;
wire   [12:0] tmp_4_fu_139_p2;
wire   [12:0] p_assign_fu_144_p3;
wire   [12:0] tmp_12_fu_176_p3;
wire   [12:0] tmp_13_fu_191_p2;
wire   [14:0] tmp_73_cast_fu_183_p1;
wire  signed [14:0] tmp_74_cast_fu_197_p1;
wire   [12:0] p_assign_3_fu_207_p2;
wire   [13:0] tmp_73_cast_cast_fu_187_p1;
wire   [13:0] tmp_17_fu_227_p2;
wire   [13:0] p_p2_cast_cast_fu_218_p1;
wire   [0:0] sel_tmp1_fu_239_p2;
wire  signed [13:0] p_assign_cast_fu_151_p1;
wire   [13:0] p_assign_4_fu_233_p2;
wire   [13:0] sel_tmp2_fu_243_p3;
wire   [0:0] sel_tmp5_demorgan_fu_255_p2;
wire   [0:0] sel_tmp5_fu_259_p2;
wire   [0:0] tmp_6_fu_155_p2;
wire   [0:0] sel_tmp6_fu_265_p2;
wire   [0:0] sel_tmp7_fu_270_p2;
wire   [0:0] tmp_9_fu_165_p2;
wire   [0:0] sel_tmp8_fu_276_p2;
wire   [0:0] sel_tmp9_fu_282_p2;
wire   [0:0] sel_tmp10_fu_288_p2;
wire  signed [14:0] p_assign_2_fu_201_p2;
wire  signed [14:0] sel_tmp2_cast_fu_251_p1;
wire   [0:0] sel_tmp16_demorgan_fu_302_p2;
wire   [0:0] sel_tmp39_fu_324_p2;
wire   [0:0] sel_tmp40_fu_330_p2;
wire   [0:0] tmp_15_fu_222_p2;
wire   [0:0] tmp53_fu_341_p2;
wire  signed [14:0] p_p3_cast_cast_fu_359_p1;
wire  signed [14:0] p_cast1_cast_fu_353_p1;
wire   [14:0] sel_tmp19_fu_365_p3;
wire   [14:0] sel_tmp20_fu_371_p3;
wire  signed [14:0] p_p_cast2_cast_fu_356_p1;
wire   [14:0] sel_tmp26_fu_378_p3;
wire   [14:0] sel_tmp34_fu_385_p3;
wire   [14:0] p_p2_cast_fu_362_p1;
wire   [14:0] sel_tmp42_fu_392_p3;




/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_const_logic_1 == ap_ce)) begin
        ap_reg_ppstg_or_cond_reg_428_pp0_it1 <= or_cond_reg_428;
        ap_reg_ppstg_p_read_reg_412_pp0_it1 <= p_read_reg_412;
        len_cast1_cast_reg_421[0] <= len_cast1_cast_fu_73_p1[0];
len_cast1_cast_reg_421[1] <= len_cast1_cast_fu_73_p1[1];
len_cast1_cast_reg_421[2] <= len_cast1_cast_fu_73_p1[2];
len_cast1_cast_reg_421[3] <= len_cast1_cast_fu_73_p1[3];
len_cast1_cast_reg_421[4] <= len_cast1_cast_fu_73_p1[4];
len_cast1_cast_reg_421[5] <= len_cast1_cast_fu_73_p1[5];
len_cast1_cast_reg_421[6] <= len_cast1_cast_fu_73_p1[6];
len_cast1_cast_reg_421[7] <= len_cast1_cast_fu_73_p1[7];
len_cast1_cast_reg_421[8] <= len_cast1_cast_fu_73_p1[8];
len_cast1_cast_reg_421[9] <= len_cast1_cast_fu_73_p1[9];
len_cast1_cast_reg_421[10] <= len_cast1_cast_fu_73_p1[10];
len_cast1_cast_reg_421[11] <= len_cast1_cast_fu_73_p1[11];
        len_read_reg_406 <= len;
        or_cond_reg_428 <= or_cond_fu_83_p2;
        p_assign_1_reg_459 <= p_assign_1_fu_115_p2;
        p_p2_reg_484 <= p_p2_fu_212_p3;
        p_p_reg_474 <= p_p_fu_160_p3;
        p_read_reg_412 <= p;
        sel_tmp25_reg_499 <= sel_tmp25_fu_312_p2;
        sel_tmp33_reg_504 <= sel_tmp33_fu_318_p2;
        sel_tmp41_reg_509 <= sel_tmp41_fu_335_p2;
        sel_tmp51_reg_514 <= sel_tmp51_fu_347_p2;
        sel_tmp_reg_469 <= sel_tmp_fu_133_p2;
        tmp_11_reg_464 <= tmp_11_fu_121_p2;
        tmp_151_reg_440 <= p[ap_const_lv32_C];
        tmp_2_reg_434 <= tmp_2_fu_89_p2;
        tmp_5_reg_447 <= tmp_5_fu_103_p2;
        tmp_7_reg_453 <= tmp_7_fu_109_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_ce) & (or_cond_reg_428 == ap_const_lv1_0))) begin
        p_p3_reg_479 <= p_p3_fu_170_p3;
        sel_tmp11_reg_489 <= sel_tmp11_fu_294_p3;
        sel_tmp18_demorgan_reg_494 <= sel_tmp18_demorgan_fu_307_p2;
    end
end
assign ap_return = ((sel_tmp51_reg_514)? p_p2_cast_fu_362_p1: sel_tmp42_fu_392_p3);
assign len_cast1_cast_fu_73_p1 = len;
assign or_cond_fu_83_p2 = (tmp_1_fu_77_p2 & rev_fu_67_p2);
assign p_assign_1_fu_115_p2 = (p ^ ap_const_lv13_1FFF);
assign p_assign_2_fu_201_p2 = ($signed(tmp_73_cast_fu_183_p1) + $signed(tmp_74_cast_fu_197_p1));
assign p_assign_3_fu_207_p2 = (ap_const_lv13_0 - p_read_reg_412);
assign p_assign_4_fu_233_p2 = (tmp_17_fu_227_p2 - p_p2_cast_cast_fu_218_p1);
assign p_assign_cast_fu_151_p1 = $signed(p_assign_fu_144_p3);
assign p_assign_fu_144_p3 = ((tmp_151_reg_440)? ap_const_lv13_0: tmp_4_fu_139_p2);
assign p_cast1_cast_fu_353_p1 = $signed(ap_reg_ppstg_p_read_reg_412_pp0_it1);
assign p_p2_cast_cast_fu_218_p1 = p_p2_fu_212_p3;
assign p_p2_cast_fu_362_p1 = p_p2_reg_484;
assign p_p2_fu_212_p3 = ((tmp_151_reg_440)? p_assign_3_fu_207_p2: p_read_reg_412);
assign p_p3_cast_cast_fu_359_p1 = $signed(p_p3_reg_479);
assign p_p3_fu_170_p3 = ((tmp_11_reg_464)? ap_const_lv13_1FFF: p_read_reg_412);
assign p_p_cast2_cast_fu_356_p1 = $signed(p_p_reg_474);
assign p_p_fu_160_p3 = ((tmp_151_reg_440)? p_assign_1_reg_459: p_read_reg_412);
assign rev_fu_67_p2 = (tmp_fu_59_p3 ^ ap_const_lv1_1);
assign sel_tmp10_fu_288_p2 = (sel_tmp8_fu_276_p2 & sel_tmp9_fu_282_p2);
assign sel_tmp11_fu_294_p3 = ((sel_tmp10_fu_288_p2)? p_assign_2_fu_201_p2: sel_tmp2_cast_fu_251_p1);
assign sel_tmp16_demorgan_fu_302_p2 = (sel_tmp5_demorgan_fu_255_p2 | tmp_5_reg_447);
assign sel_tmp18_demorgan_fu_307_p2 = (sel_tmp16_demorgan_fu_302_p2 | tmp_7_reg_453);
assign sel_tmp19_fu_365_p3 = ((sel_tmp18_demorgan_reg_494)? sel_tmp11_reg_489: p_p3_cast_cast_fu_359_p1);
assign sel_tmp1_fu_239_p2 = (tmp_2_reg_434 & sel_tmp_reg_469);
assign sel_tmp20_fu_371_p3 = ((ap_reg_ppstg_or_cond_reg_428_pp0_it1)? p_cast1_cast_fu_353_p1: sel_tmp19_fu_365_p3);
assign sel_tmp25_fu_312_p2 = (sel_tmp6_fu_265_p2 & tmp_6_fu_155_p2);
assign sel_tmp26_fu_378_p3 = ((sel_tmp25_reg_499)? ap_const_lv15_0: sel_tmp20_fu_371_p3);
assign sel_tmp2_cast_fu_251_p1 = $signed(sel_tmp2_fu_243_p3);
assign sel_tmp2_fu_243_p3 = ((sel_tmp1_fu_239_p2)? p_assign_cast_fu_151_p1: p_assign_4_fu_233_p2);
assign sel_tmp33_fu_318_p2 = (sel_tmp8_fu_276_p2 & tmp_9_fu_165_p2);
assign sel_tmp34_fu_385_p3 = ((sel_tmp33_reg_504)? p_p_cast2_cast_fu_356_p1: sel_tmp26_fu_378_p3);
assign sel_tmp39_fu_324_p2 = (sel_tmp16_demorgan_fu_302_p2 ^ ap_const_lv1_1);
assign sel_tmp40_fu_330_p2 = (tmp_7_reg_453 & sel_tmp39_fu_324_p2);
assign sel_tmp41_fu_335_p2 = (sel_tmp40_fu_330_p2 & tmp_6_fu_155_p2);
assign sel_tmp42_fu_392_p3 = ((sel_tmp41_reg_509)? ap_const_lv15_0: sel_tmp34_fu_385_p3);
assign sel_tmp51_fu_347_p2 = (tmp53_fu_341_p2 & sel_tmp40_fu_330_p2);
assign sel_tmp5_demorgan_fu_255_p2 = (or_cond_reg_428 | tmp_2_reg_434);
assign sel_tmp5_fu_259_p2 = (sel_tmp5_demorgan_fu_255_p2 ^ ap_const_lv1_1);
assign sel_tmp6_fu_265_p2 = (tmp_5_reg_447 & sel_tmp5_fu_259_p2);
assign sel_tmp7_fu_270_p2 = (tmp_6_fu_155_p2 ^ ap_const_lv1_1);
assign sel_tmp8_fu_276_p2 = (sel_tmp6_fu_265_p2 & sel_tmp7_fu_270_p2);
assign sel_tmp9_fu_282_p2 = (tmp_9_fu_165_p2 ^ ap_const_lv1_1);
assign sel_tmp_fu_133_p2 = (tmp_fu_59_p3 | tmp_1_not_fu_127_p2);
assign tmp53_fu_341_p2 = (tmp_15_fu_222_p2 & sel_tmp7_fu_270_p2);
assign tmp_11_fu_121_p2 = (borderType == ap_const_lv4_0? 1'b1: 1'b0);
assign tmp_12_fu_176_p3 = {{len_read_reg_406}, {ap_const_lv1_0}};
assign tmp_13_fu_191_p2 = (p_p_fu_160_p3 ^ ap_const_lv13_1FFF);
assign tmp_15_fu_222_p2 = (p_p2_fu_212_p3 < len_cast1_cast_reg_421? 1'b1: 1'b0);
assign tmp_17_fu_227_p2 = ($signed(tmp_73_cast_cast_fu_187_p1) + $signed(ap_const_lv14_3FFE));
assign tmp_1_fu_77_p2 = ($signed(len_cast1_cast_fu_73_p1) > $signed(p)? 1'b1: 1'b0);
assign tmp_1_not_fu_127_p2 = (tmp_1_fu_77_p2 ^ ap_const_lv1_1);
assign tmp_2_fu_89_p2 = (borderType == ap_const_lv4_1? 1'b1: 1'b0);
assign tmp_4_fu_139_p2 = ($signed(len_cast1_cast_reg_421) + $signed(ap_const_lv13_1FFF));
assign tmp_5_fu_103_p2 = (borderType == ap_const_lv4_2? 1'b1: 1'b0);
assign tmp_6_fu_155_p2 = (len_read_reg_406 == ap_const_lv12_1? 1'b1: 1'b0);
assign tmp_73_cast_cast_fu_187_p1 = tmp_12_fu_176_p3;
assign tmp_73_cast_fu_183_p1 = tmp_12_fu_176_p3;
assign tmp_74_cast_fu_197_p1 = $signed(tmp_13_fu_191_p2);
assign tmp_7_fu_109_p2 = (borderType == ap_const_lv4_4? 1'b1: 1'b0);
assign tmp_9_fu_165_p2 = ($signed(p_p_fu_160_p3) < $signed(len_cast1_cast_reg_421)? 1'b1: 1'b0);
assign tmp_fu_59_p3 = p[ap_const_lv32_C];
always @ (posedge ap_clk)
begin
    len_cast1_cast_reg_421[12] <= 1'b0;
end



endmodule //toThreshold_borderInterpolate

